[package]
name = "cgp_lcm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cgp_lcm"
path = "src/main.rs"

[dependencies]
rand = { version = "0.8.5", features=["small_rng"] }
rand_distr = "0.4"
rayon = "1.8"
rustfft = "6.1"
num-complex = "0.4"
ahash = "0.8"
dashmap = "5.5"
lru = "0.17.0"
ndarray = "0.17.2"
