#!/usr/bin/env python3
"""
CMA-ES によるADF-CGP ハイパーパラメータ探索
============================================

探索対象:
  - N_LAYERS       : 2〜5 (整数)
  - LAYER_LEN      : 各層共通のノード数 4〜64 (整数)
  - N_ADF_PER_LAYER: 各ADF層共通のADF数 1〜8 (整数)
  - ELITE          : 8〜128 (整数)
  - POP_SIZE       : 128〜8192 (整数)
  - VEC_LEN        : 64〜2048 (整数)
  - PROB_EML       : 0.0〜1.0 (実数)
  - MUT_STOP_PROB  : 0.05〜0.6 (実数) ← 追加: Chromosome突然変異の幾何分布停止確率
  - MUT_MAX_TARGETS: 1〜8 (整数)      ← 追加: Genome突然変異の最大対象Chromosome数

評価方法:
  各候補パラメータでRustソースを生成 → cargo build --release →
  30秒間実行 → stdout から最終行の acc を取得
  目的関数 = -acc (最小化)

使い方:
  python3 cmaes_search.py [--src SRC_RS] [--out OUT_DIR] [--budget N] [--time SEC]

依存:
  pip install cma
  cargo / rustc が PATH 上にあること
"""

import argparse
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
import textwrap
import time
from pathlib import Path
from typing import Optional

import cma

# ─── デフォルト設定 ───────────────────────────────────────────────────────────

DEFAULT_SRC     = "src/main.rs"   # Rustソースの相対パス (プロジェクトルートから)
DEFAULT_OUT     = "cmaes_results" # 結果ディレクトリ
DEFAULT_BUDGET  = 1000             # CMA-ES の最大評価回数
DEFAULT_TIME    = 30              # 各評価の実行秒数

# ─── ハイパーパラメータ定義 ──────────────────────────────────────────────────

# CMA-ES は実数ベクトルを操作する。
# 各パラメータを以下のスケーリングで扱う:
#   整数パラメータ → round(clip(x, lo, hi))
#   実数パラメータ → clip(x, lo, hi)

PARAM_DEFS = [
    # (name,             lo,    hi,   init,  is_int, log_scale)
    ("N_LAYERS",          2,     9,    4,    True,   True),
    ("LAYER_LEN",         4,    128,   32,   True,   True),
    ("LAYER_LEN_LAST",    4,   1024,   64,  True,   True),
    ("N_ADF_PER_LAYER",   1,    32,    12,    True,   True),
    ("ELITE",             8,   256,   24,    True,   True),
    ("POP_SIZE",         48,  16384, 1024,   True,   True),
    ("VEC_LEN",          64,  8192,  1024,   True,   True),
    ("PROB_EML",        0.0,   1.0,   0.3,  False,  False),
    ("A",              -1.5,   2.0,   0.01, False,  False),
    ("B",               0.0,   1.0,   0.5,  False,  False),
    ("C",              -1.5,   2.0,   0.01, False,  False),
    ("D",               0.0,   1.0,   0.5,  False,  False),
    ("HILO",             5.0,  5.000001,  5.0,  False,  True),
    ("P",               0.5,   3,   1.5,  False,  True),
    # ── 突然変異率パラメータ (追加) ──────────────────────────────────────────
    # Chromosome::mutate における幾何分布の停止確率。
    # 小さいほど多くのノードが変異する（探索的）、大きいほど少数変異（局所的）。
    ("MUT_STOP_PROB",   0.001,  12,  6, False,  False),
    # Genome::mutate で一度に変異させる Chromosome の最大数。
    ("MUT_MAX_TARGETS",  1,     8,    3,    True,   True),
]


# ─── ユーティリティ ──────────────────────────────────────────────────────────

def encode(params: dict) -> list[float]:
    """パラメータ辞書 → CMA-ES ベクトル"""
    vec = []
    for name, lo, hi, init, is_int, log_scale in PARAM_DEFS:
        v = params[name]
        if log_scale:
            vec.append(math.log(max(v, 1e-6)))
        else:
            vec.append(float(v))
    return vec


def decode(x: list[float]) -> dict:
    """CMA-ES ベクトル → パラメータ辞書"""
    result = {}
    for i, (name, lo, hi, init, is_int, log_scale) in enumerate(PARAM_DEFS):
        v = x[i]
        if log_scale:
            v = math.exp(v)
        v = max(lo, min(hi, v))
        if is_int:
            v = int(round(v))
            v = max(int(lo), min(int(hi), v))
        result[name] = v
    return result


def initial_x() -> list[float]:
    params = {name: init for name, lo, hi, init, is_int, log_scale in PARAM_DEFS}
    return encode(params)


def initial_sigma() -> float:
    return 5.0


# ─── Rustソース生成 ──────────────────────────────────────────────────────────

RUST_TEMPLATE = """\
// AUTO-GENERATED by cmaes_search.py — DO NOT EDIT
use ahash::AHasher;
use dashmap::DashMap;
use num_complex::Complex;
use rand::rngs::SmallRng;
use rand::{{Rng, SeedableRng}};
use rayon::prelude::*;
use std::hash::{{Hash, Hasher}};
use std::sync::Arc;

// ─── アーキテクチャ ハイパーパラメータ ───────────────────────────────────────
const N_LAYERS: usize = {N_LAYERS};
const LAYER_LEN: [usize; N_LAYERS] = [{LAYER_LEN_ARR}];
const N_INPUTS_MAIN: usize = 2;
const N_INPUTS_ADF: usize = 3;
const N_ADF_PER_LAYER: [usize; N_LAYERS - 1] = [{N_ADF_ARR}];

const ONE_SIG: Sig = 0xFFFF_FFFF_FFFF_FFFFu64;
const VEC_LEN: usize = {VEC_LEN};
const POP_SIZE: usize = {POP_SIZE};
const ELITE: usize = {ELITE};
const N_GEN: usize = 99999999;  // 時間制限で止める
const PROB_EML: f64 = {PROB_EML};
const A: f64 = {A};
const B: f64 = {B};
const C: f64 = {C};
const D: f64 = {D};
const HILO: f64 = {HILO};
const P: f64 = {P};

// ─── 突然変異率パラメータ ────────────────────────────────────────────────────
/// Chromosome::mutate の幾何分布停止確率。
/// while rng.gen::<f64>() > MUT_STOP_PROB で使用。
/// 小さいほど多ノード変異、大きいほど少数変異。
const MUT_STOP_PROB: f64 = {MUT_STOP_PROB};

/// Genome::mutate で一度に変異させる Chromosome の最大数。
const MUT_MAX_TARGETS: usize = {MUT_MAX_TARGETS};

// ─── カリキュラム学習 ────────────────────────────────────────────────────────
const CURRICULUM_RAMP_GENS: usize = 1;
const INTER_WEIGHT_MAX: f64 = 1.0;

// ─── adf_cache 上限 ──────────────────────────────────────────────────────────
const ADF_CACHE_MAX: usize = 1 << 18;

// ─── バッチ設定 ──────────────────────────────────────────────────────────────
const N_BATCHES: usize = 1;

{BODY}
"""

# ─── ここに元の関数群を埋め込むため、テンプレート末尾 {BODY} に挿入する ─────

RUST_BODY = r"""
// ─── レイヤー設定ヘルパー ─────────────────────────────────────────────────────

#[inline]
fn is_top(layer_idx: usize) -> bool {
    layer_idx == N_LAYERS - 1
}
#[inline]
fn layer_len(layer_idx: usize) -> usize {
    LAYER_LEN[layer_idx]
}
#[inline]
fn layer_n_ext(layer_idx: usize) -> usize {
    if is_top(layer_idx) { N_INPUTS_MAIN } else { N_INPUTS_ADF }
}
#[inline]
fn layer_n_adf(layer_idx: usize) -> usize {
    N_ADF_PER_LAYER[layer_idx]
}
#[inline]
fn layer_n_funcs(layer_idx: usize) -> usize {
    if layer_idx == 0 { 1 } else { 1 + layer_n_adf(layer_idx - 1) }
}

fn selectfunc(max: u8, rng: &mut SmallRng) -> u8 {
    if rng.gen::<f64>() < PROB_EML { return 0; }
    rng.gen_range(0..max)
}

// ─── 複素数ユーティリティ ─────────────────────────────────────────────────────

#[inline(always)]
fn clamp(z: Complex<f64>) -> Complex<f64> {
    const M: f64 = 15.0;
    Complex::new(z.re.clamp(-M, M), z.im.clamp(-M, M))
}
#[inline(always)]
fn safe_log(z: Complex<f64>) -> Complex<f64> {
    const EPS: f64 = 1e-6;
    if z.norm_sqr() < EPS * EPS { Complex::new(EPS, 0.0).ln() } else { z.ln() }
}
#[inline(always)]
fn eml(a: Complex<f64>, b: Complex<f64>) -> Complex<f64> {
    clamp(a).exp() - safe_log(b)
}
fn eml_vec(x: &[Complex<f64>], y: &[Complex<f64>]) -> Vec<Complex<f64>> {
    x.iter().zip(y).map(|(&a, &b)| eml(a, b)).collect()
}

// ─── Chromosome ───────────────────────────────────────────────────────────────

#[derive(Clone)]
struct Chromosome {
    layer_idx: usize,
    conn: Box<[[u16; 2]]>,
    func: Box<[u8]>,
}

impl Chromosome {
    fn random(layer_idx: usize, rng: &mut SmallRng) -> Self {
        let n = layer_len(layer_idx);
        let n_ext = layer_n_ext(layer_idx);
        let n_f = layer_n_funcs(layer_idx) as u8;
        let conn = (0..n)
            .map(|i| { let m = (n_ext + i) as u16; [((1.0 - rng.gen::<f64>().powf(P)) * m as f64).floor() as u16, ((1.0 - rng.gen::<f64>().powf(P)) * m as f64).floor() as u16] })
            .collect::<Vec<_>>().into_boxed_slice();
        let func = (0..n).map(|_| selectfunc(n_f, rng)).collect::<Vec<_>>().into_boxed_slice();
        Self { layer_idx, conn, func }
    }

    fn active_and_sig(&self) -> (Vec<usize>, u64) {
        let n = layer_len(self.layer_idx);
        let n_ext = layer_n_ext(self.layer_idx);
        let total = n_ext + n;
        let mut active = vec![false; total];
        active[total - 1] = true;
        for i in (0..n).rev() {
            if !active[n_ext + i] { continue; }
            active[self.conn[i][0] as usize] = true;
            active[self.conn[i][1] as usize] = true;
        }
        let mut h = AHasher::default();
        (self.layer_idx as u8).hash(&mut h);
        let list: Vec<usize> = (0..total).filter(|&i| active[i])
            .inspect(|&abs| {
                if abs >= n_ext {
                    let i = abs - n_ext;
                    self.conn[i][0].hash(&mut h); self.conn[i][1].hash(&mut h);
                    self.func[i].hash(&mut h); abs.hash(&mut h);
                }
            }).collect();
        (list, h.finish())
    }

    fn mutate(&self, rng: &mut SmallRng) -> Self {
        let mut conn = self.conn.to_vec();
        let mut func = self.func.to_vec();
        let n = layer_len(self.layer_idx);
        let n_ext = layer_n_ext(self.layer_idx);
        let n_f = layer_n_funcs(self.layer_idx) as u8;
        // MUT_STOP_PROB: 対数一様分布の最大値。大きいほど多くのノードを変異させる。
        let mut n_mut = (rng.gen::<f64>() * MUT_STOP_PROB).exp() as usize + 1;
        for _ in 0..n_mut {
            let i = rng.gen_range(0..n);
            let max = (n_ext + i) as u16;
            match rng.gen_range(0..3u8) {
                0 => conn[i][0] = ((1.0 - rng.gen::<f64>().powf(P)) * max as f64).floor() as u16,
                1 => conn[i][1] = ((1.0 - rng.gen::<f64>().powf(P)) * max as f64).floor() as u16,
                _ => func[i] = selectfunc(n_f, rng),
            }
            if rng.gen::<f64>() < 0.05 {
                conn[i][rng.gen_range(0..2)] = rng.gen_range(0..n_ext as u16);
            }
        }
        Self { layer_idx: self.layer_idx, conn: conn.into_boxed_slice(), func: func.into_boxed_slice() }
    }

    fn mix(&self, rng: &mut SmallRng, other: &Chromosome) -> Self {
        let (active2, _) = other.active_and_sig();
        let n_ext = layer_n_ext(self.layer_idx);
        let mut conn = self.conn.to_vec();
        let mut func = self.func.to_vec();
        let mut cands: Vec<usize> = active2.into_iter().filter(|&i| i >= n_ext).collect();
        if !cands.is_empty() {
            let n_copy = rng.gen_range(1..=cands.len());
            for i in 0..n_copy.min(cands.len()) {
                let j = rng.gen_range(i..cands.len());
                cands.swap(i, j);
                let local = cands[i] - n_ext;
                conn[local] = other.conn[local];
                func[local] = other.func[local];
            }
        }
        Self { layer_idx: self.layer_idx, conn: conn.into_boxed_slice(), func: func.into_boxed_slice() }
    }
}

// ─── Genome ───────────────────────────────────────────────────────────────────

#[derive(Clone)]
struct Genome { layers: Vec<Vec<Chromosome>> }

impl Genome {
    fn random(rng: &mut SmallRng) -> Self {
        let layers = (0..N_LAYERS).map(|li| {
            let count = if is_top(li) { 1 } else { layer_n_adf(li) };
            (0..count).map(|_| Chromosome::random(li, rng)).collect()
        }).collect();
        Self { layers }
    }

    fn mutate(&self, rng: &mut SmallRng) -> Self {
        let mut g = self.clone();
        let totals: Vec<usize> = (0..N_LAYERS)
            .map(|li| if is_top(li) { 1 } else { layer_n_adf(li) }).collect();
        let grand_total: usize = totals.iter().sum();
        // MUT_MAX_TARGETS: 一度に変異させる Chromosome の最大数
        let n_targets = rng.gen_range(1..=MUT_MAX_TARGETS.min(grand_total));
        for _ in 0..n_targets {
            let mut t = rng.gen_range(0..grand_total);
            for (li, &cnt) in totals.iter().enumerate() {
                if t < cnt { g.layers[li][t] = self.layers[li][t].mutate(rng); break; }
                t -= cnt;
            }
        }
        g
    }

    fn mix(&self, rng: &mut SmallRng, other: &Genome) -> Self {
        let mut g = self.clone();
        for li in 0..N_LAYERS {
            let cnt = if is_top(li) { 1 } else { layer_n_adf(li) };
            for k in 0..cnt {
                if rng.gen::<f64>() < 0.5 {
                    g.layers[li][k] = self.layers[li][k].mix(rng, &other.layers[li][k]);
                }
            }
        }
        g
    }
}

// ─── Signature ────────────────────────────────────────────────────────────────

type Sig = u64;

#[inline]
fn make_sig(a: Sig, b: Sig, func_id: u8) -> Sig {
    let mut x = a ^ ((func_id as u64).wrapping_mul(0x9e3779b97f4a7c15));
    x ^= b.wrapping_mul(0x6c62272e07bb0142);
    x ^= x >> 30; x = x.wrapping_mul(0xbf58476d1ce4e5b9);
    x ^= x >> 27; x = x.wrapping_mul(0x94d049bb133111eb);
    x ^ (x >> 31)
}

fn genome_key(all_sigs: &[Vec<Sig>]) -> u64 {
    let mut h = AHasher::default();
    for layer_sigs in all_sigs { for &s in layer_sigs { s.hash(&mut h); } }
    h.finish()
}

// ─── Cache ────────────────────────────────────────────────────────────────────

type ArcVec = Arc<[Complex<f64>]>;
type AdfKey = (Sig, Sig, Sig, Sig);
type Score = (f64, f64);

struct NodeBuf { sigs: Vec<Sig>, vals: Vec<ArcVec> }

impl NodeBuf {
    fn new(total: usize) -> Self {
        let dummy: ArcVec = Arc::from(vec![Complex::new(0.0, 0.0); VEC_LEN].into_boxed_slice());
        Self { sigs: vec![0u64; total], vals: vec![dummy; total] }
    }
    #[inline] fn set(&mut self, idx: usize, sig: Sig, val: ArcVec) { self.sigs[idx] = sig; self.vals[idx] = val; }
    #[inline] fn sig(&self, idx: usize) -> Sig { self.sigs[idx] }
    #[inline] fn val(&self, idx: usize) -> &ArcVec { &self.vals[idx] }
}

#[inline]
fn node_get_or_compute(sig: Sig, v0: &[Complex<f64>], v1: &[Complex<f64>], ev: &Evaluator) -> ArcVec {
    if let Some(v) = ev.node_cache.get(&sig) { return Arc::clone(&*v); }
    let out: ArcVec = Arc::from(eml_vec(v0, v1).into_boxed_slice());
    ev.node_cache.entry(sig).or_insert_with(|| Arc::clone(&out));
    out
}

// ─── Dataset ──────────────────────────────────────────────────────────────────

fn target_fn(x: Complex<f64>) -> Complex<f64> { (x * x * x - x).sin() + x.sin()  }

fn make_batch(rng: &mut SmallRng, x_range: (f64, f64))
    -> ([Vec<Complex<f64>>; N_INPUTS_MAIN], Vec<Complex<f64>>)
{
    let (lo, hi) = x_range;
    let xs: Vec<Complex<f64>> = (0..VEC_LEN)
        .map(|_| Complex::new(lo + rng.gen::<f64>() * (hi - lo), 0.0)).collect();
    let one = vec![Complex::new(1.0, 0.0); VEC_LEN];
    let ys = xs.iter().map(|&x| target_fn(x)).collect();
    ([xs, one], ys)
}

struct Dataset {
    batches: Vec<([Vec<Complex<f64>>; N_INPUTS_MAIN], Vec<Complex<f64>>)>,
    batch_sig: Sig,
}

impl Dataset {
    /// 固定データセット: 起動時に一度だけ生成し、以降は変更しない。
    /// batch_sig も固定値になるため、世代をまたいだキャッシュが正しく機能する。
    fn new_fixed(rng: &mut SmallRng) -> Self {
        let batches: Vec<_> = (0..N_BATCHES).map(|_| make_batch(rng, (-HILO, HILO))).collect();
        let batch_sig = Self::compute_sig(&batches);
        Self { batches, batch_sig }
    }
    fn compute_sig(batches: &[([Vec<Complex<f64>>; N_INPUTS_MAIN], Vec<Complex<f64>>)]) -> Sig {
        let mut h = AHasher::default();
        for (inputs, _) in batches { for z in inputs[0].iter().take(8) { z.re.to_bits().hash(&mut h); } }
        h.finish()
    }
}

// ─── Evaluator ────────────────────────────────────────────────────────────────

struct Evaluator {
    node_cache: DashMap<Sig, ArcVec>,
    adf_cache: DashMap<AdfKey, (Sig, ArcVec)>,
    /// 固定データセット運用では fitness_cache はゲノムが同一なら永続的に有効。
    /// 世代をまたいで保持し、新規ゲノムのみ計算する。
    fitness_cache: DashMap<u64, Score>,
    score_cache: DashMap<(Sig, Sig), Score>,
}

impl Evaluator {
    fn new() -> Self {
        Self {
            node_cache: DashMap::with_capacity(1 << 17),
            adf_cache: DashMap::with_capacity(1 << 16),
            fitness_cache: DashMap::with_capacity(POP_SIZE * 8),
            score_cache: DashMap::with_capacity(1 << 17),
        }
    }

    /// 固定データセット運用向けリセット。
    /// - node_cache: メモリ節約のため世代ごとにクリア（再計算コストは小さい）。
    /// - fitness_cache / adf_cache / score_cache:
    ///   データセットが変わらないため保持。同一ゲノムは再評価不要。
    ///   ただし adf_cache がメモリ上限を超えたら解放する。
    fn reset_generation(&self) {
        self.node_cache.clear();
        if self.adf_cache.len() > ADF_CACHE_MAX {
            self.adf_cache.clear();
            self.score_cache.clear();
            // fitness_cache は adf_cache に依存しないので保持してよい
        }
    }

    fn get_node_score(&self, batch_sig: Sig, node_sig: Sig, val: &ArcVec, target: &[Complex<f64>],
        p_buf: &mut [f64], t_buf: &mut [f64], order_buf: &mut [usize], rank_buf: &mut [i64]) -> Score
    {
        let key = (batch_sig, node_sig);
        if let Some(s) = self.score_cache.get(&key) { return *s; }
        let s = score_and_acc_into(val, target, p_buf, t_buf, order_buf, rank_buf);
        self.score_cache.insert(key, s); s
    }
}

// ─── 評価指標 ─────────────────────────────────────────────────────────────────

fn pearson_raw(x: &[f64], y: &[f64]) -> f64 {
    let n = x.len() as f64;
    let mx = x.iter().sum::<f64>() / n;
    let my = y.iter().sum::<f64>() / n;
    let (mut num, mut dx, mut dy) = (0.0, 0.0, 0.0f64);
    for (&xi, &yi) in x.iter().zip(y) {
        let a = xi - mx; let b = yi - my;
        num += a * b; dx += a * a; dy += b * b;
    }
    if dx < 1e-12 || dy < 1e-12 { 0.0 } else { num / (dx.sqrt() * dy.sqrt()) }
}

#[inline]
fn chatterjee_from_ranks(sorted_idx: &[usize], ranks: &[i64]) -> f64 {
    let s: i64 = sorted_idx.windows(2).map(|w| (ranks[w[0]] - ranks[w[1]]).abs()).sum();
    let n = sorted_idx.len() as f64;
    1.0 - 3.0 * s as f64 / (n * n - 1.0)
}

fn score_and_acc_into(pred: &[Complex<f64>], target: &[Complex<f64>],
    p_buf: &mut [f64], t_buf: &mut [f64], order_buf: &mut [usize], rank_buf: &mut [i64]) -> (f64, f64)
{
    let n = pred.len();
    let extractors: [fn(Complex<f64>) -> f64; 4] = [|z| z.re, |z| z.im, |z| z.norm(), |z| z.arg()];
    let mut total_score = 0.0f64;
    let mut max_pearson = 0.0f64;
    let mut p_rank_buf = vec![0i64; n];
    let mut t_order_buf = vec![0usize; n];
    for ext in extractors {
        for k in 0..n { p_buf[k] = ext(pred[k]); t_buf[k] = ext(target[k]); }
        for k in 0..n { order_buf[k] = k; }
        order_buf[..n].sort_unstable_by(|&a, &b| p_buf[a].partial_cmp(&p_buf[b]).unwrap_or(std::cmp::Ordering::Equal));
        for (r, &i) in order_buf[..n].iter().enumerate() { p_rank_buf[i] = r as i64; }
        for k in 0..n { t_order_buf[k] = k; }
        t_order_buf[..n].sort_unstable_by(|&a, &b| t_buf[a].partial_cmp(&t_buf[b]).unwrap_or(std::cmp::Ordering::Equal));
        for (r, &i) in t_order_buf[..n].iter().enumerate() { rank_buf[i] = r as i64; }
        let c_fwd = chatterjee_from_ranks(&order_buf[..n], rank_buf);
        let c_bwd = chatterjee_from_ranks(&t_order_buf[..n], &p_rank_buf);
        let pe = pearson_raw(&p_buf[..n], &t_buf[..n]).abs();
        total_score += (((c_fwd.max(0.0).powf(C) + c_bwd.max(0.0).powf(C)) / 2.0) * (1.0 - D) + pe.powf(C) * D).powf(1.0 / C);
        if pe > max_pearson { max_pearson = pe; }
    }
    (total_score / 4.0, max_pearson)
}

// ─── 汎用 ADF 実行 ────────────────────────────────────────────────────────────

fn exec_adf(
    layer_idx: usize, c: &Chromosome, c_sig: Sig, active: &[usize],
    in0_sig: Sig, in0: &ArcVec, in1_sig: Sig, in1: &ArcVec, one: &ArcVec,
    genome: &Genome, all_sigs: &[Vec<Sig>], all_acts: &[Vec<Vec<usize>>],
    batch_sig: Sig, ev: &Evaluator,
) -> (Sig, ArcVec) {
    let key: AdfKey = (batch_sig, c_sig, in0_sig, in1_sig);
    if let Some(v) = ev.adf_cache.get(&key) { return (v.0, Arc::clone(&v.1)); }
    let n_ext = N_INPUTS_ADF;
    let total = n_ext + layer_len(layer_idx);
    let mut buf = NodeBuf::new(total);
    buf.set(0, in0_sig, Arc::clone(in0));
    buf.set(1, in1_sig, Arc::clone(in1));
    buf.set(2, ONE_SIG, Arc::clone(one));
    for &abs in active {
        if abs < n_ext { continue; }
        let i = abs - n_ext;
        let c0 = c.conn[i][0] as usize;
        let c1 = c.conn[i][1] as usize;
        let s0 = buf.sig(c0); let s1 = buf.sig(c1);
        let f = c.func[i] as usize;
        let (sig, val) = if f == 0 || layer_idx == 0 {
            let sig = make_sig(s0, s1, 0);
            let val = node_get_or_compute(sig, buf.val(c0), buf.val(c1), ev);
            (sig, val)
        } else {
            let sub_li = layer_idx - 1;
            let sub_idx = (f - 1).min(layer_n_adf(sub_li) - 1);
            exec_adf(sub_li, &genome.layers[sub_li][sub_idx], all_sigs[sub_li][sub_idx],
                &all_acts[sub_li][sub_idx], s0, buf.val(c0), s1, buf.val(c1), one,
                genome, all_sigs, all_acts, batch_sig, ev)
        };
        buf.set(abs, sig, val);
    }
    let result = (buf.sig(total - 1), Arc::clone(buf.val(total - 1)));
    ev.adf_cache.entry(key).or_insert_with(|| result.clone());
    result
}

// ─── 最終出力層 実行 ──────────────────────────────────────────────────────────

fn exec_top(
    genome: &Genome, top_active: &[usize], all_sigs: &[Vec<Sig>], all_acts: &[Vec<Vec<usize>>],
    ext: &[Vec<Complex<f64>>; N_INPUTS_MAIN], target: &[Complex<f64>],
    batch_sig: Sig, ev: &Evaluator,
    p_buf: &mut [f64], t_buf: &mut [f64], order_buf: &mut [usize], rank_buf: &mut [i64],
) -> (ArcVec, Sig, f64, usize) {
    let top_li = N_LAYERS - 1;
    let c = &genome.layers[top_li][0];
    let n_ext = N_INPUTS_MAIN;
    let total = n_ext + layer_len(top_li);
    let mut buf = NodeBuf::new(total);
    for i in 0..n_ext { buf.set(i, i as Sig + 1, Arc::from(ext[i].as_slice())); }
    let one_arc: ArcVec = Arc::from(ext[1].as_slice());
    let mut sum_score = 0.0; let mut count = 0;
    for &abs in top_active {
        if abs < n_ext { continue; }
        let i = abs - n_ext;
        let c0 = c.conn[i][0] as usize; let c1 = c.conn[i][1] as usize;
        let s0 = buf.sig(c0); let s1 = buf.sig(c1);
        let f = c.func[i] as usize;
        let (sig, val) = if f == 0 || top_li == 0 {
            let sig = make_sig(s0, s1, 0);
            let val = node_get_or_compute(sig, buf.val(c0), buf.val(c1), ev);
            (sig, val)
        } else {
            let sub_li = top_li - 1;
            let sub_idx = (f - 1).min(layer_n_adf(sub_li) - 1);
            exec_adf(sub_li, &genome.layers[sub_li][sub_idx], all_sigs[sub_li][sub_idx],
                &all_acts[sub_li][sub_idx], s0, buf.val(c0), s1, buf.val(c1), &one_arc,
                genome, all_sigs, all_acts, batch_sig, ev)
        };
        let (s, _) = ev.get_node_score(batch_sig, sig, &val, target, p_buf, t_buf, order_buf, rank_buf);
        sum_score += s; count += 1;
        buf.set(abs, sig, val);
    }
    let out_sig = buf.sig(total - 1);
    (Arc::clone(buf.val(total - 1)), out_sig, sum_score, count)
}

// ─── Fitness 評価 ─────────────────────────────────────────────────────────────

fn eval(g: &Genome, ds: &Dataset, ev: &Evaluator, inter_weight: f64) -> (f64, f64) {
    let top_li = N_LAYERS - 1;
    let all_data: Vec<Vec<(Vec<usize>, Sig)>> = (0..N_LAYERS)
        .map(|li| g.layers[li].iter().map(|c| c.active_and_sig()).collect()).collect();
    let all_sigs: Vec<Vec<Sig>> = all_data.iter()
        .map(|layer| layer.iter().map(|d| d.1).collect()).collect();
    let all_acts: Vec<Vec<Vec<usize>>> = all_data.into_iter()
        .map(|layer| layer.into_iter().map(|d| d.0).collect()).collect();
    let top_active = &all_acts[top_li][0];
    let genome_base = genome_key(&all_sigs);
    let top_sig = all_sigs[top_li][0];
    // 固定データセット: batch_sig は不変なのでキャッシュキーとして安全に使える。
    // inter_weight もキーに含める（世代が異なると値が変わるため）。
    let gkey = make_sig(make_sig(genome_base, ds.batch_sig, 0),
                        inter_weight.to_bits(), 1);
    if let Some(v) = ev.fitness_cache.get(&gkey) { return *v; }
    let mut p_buf = vec![0.0f64; VEC_LEN];
    let mut t_buf = vec![0.0f64; VEC_LEN];
    let mut order_buf = vec![0usize; VEC_LEN];
    let mut rank_buf = vec![0i64; VEC_LEN];
    let mut total_loss = 0.0; let mut total_acc = 0.0;
    for (inputs, target) in &ds.batches {
        let (pred, out_sig, sum_score, count) = exec_top(
            g, top_active, &all_sigs, &all_acts, inputs, target, ds.batch_sig, ev,
            &mut p_buf, &mut t_buf, &mut order_buf, &mut rank_buf);
        let (final_s, final_a) = ev.get_node_score(ds.batch_sig, out_sig, &pred, target,
            &mut p_buf, &mut t_buf, &mut order_buf, &mut rank_buf);
        let avg_inter = if count > 0 { sum_score / count as f64 } else { 0.0 };
        let combined = final_s * (1.0 - inter_weight) + avg_inter * inter_weight;
        total_loss += ((1.0 - combined).powf(A) * B + (1.0 - final_a).powf(A) * (1.0 - B)).powf(1.0 / A);
        total_acc += final_a;
    }
    let _ = top_sig;
    let n = ds.batches.len() as f64;
    let res = (total_loss / n, total_acc / n);
    ev.fitness_cache.insert(gkey, res); res
}

// ─── Main ─────────────────────────────────────────────────────────────────────

fn main() {
    assert_eq!(LAYER_LEN.len(), N_LAYERS, "LAYER_LEN の要素数は N_LAYERS に合わせてください");
    assert_eq!(N_ADF_PER_LAYER.len(), N_LAYERS - 1, "N_ADF_PER_LAYER の要素数は N_LAYERS-1 に合わせてください");
    assert!(N_LAYERS >= 1, "N_LAYERS は 1 以上にしてください");

    eprintln!(
        "ADF-CGP  N_LAYERS={N_LAYERS}  N_ADF_PER_LAYER={:?}  LAYER_LEN={:?}  POP={POP_SIZE}  BATCHES={N_BATCHES}  MUT_STOP_PROB={MUT_STOP_PROB}  MUT_MAX_TARGETS={MUT_MAX_TARGETS}",
        N_ADF_PER_LAYER, LAYER_LEN,
    );

    let mut rng = SmallRng::seed_from_u64(42);
    // 固定データセット: 起動時に一度だけ生成する
    let ds = Dataset::new_fixed(&mut rng);
    let mut pop: Vec<Genome> = (0..POP_SIZE).map(|_| Genome::random(&mut rng)).collect();
    let evaluator = Evaluator::new();

    for gen in 0..N_GEN {
        // 固定データセット運用: バッチ変更なし。node_cache のみクリア。
        evaluator.reset_generation();
        let inter_weight = INTER_WEIGHT_MAX * (gen as f64 / CURRICULUM_RAMP_GENS as f64).min(1.0);
        let mut scored: Vec<(f64, f64, Genome)> = pop
            .par_iter()
            .map(|g| { let (l, a) = eval(g, &ds, &evaluator, inter_weight); (l, a, g.clone()) })
            .collect();
        scored.sort_unstable_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal));
        // CMAES_OUTPUT フォーマット: 最終行に acc を出力
        println!(
            "CMAES_ACC gen={} loss={:.10} acc={:.10}",
            gen, scored[0].0, scored[0].1
        );
        let elites: Vec<Genome> = scored[..ELITE].iter().map(|x| x.2.clone()).collect();
        let mut next = elites;
        while next.len() < POP_SIZE {
            let p1 = &scored[rng.gen_range(0..ELITE)].2;
            let p2 = &scored[rng.gen_range(0..ELITE)].2;
            let child = match rng.gen_range(0..3u8) {
                0 => p1.mix(&mut rng, p2),
                1 => p1.mutate(&mut rng),
                _ => p1.mix(&mut rng, p2).mutate(&mut rng),
            };
            next.push(child);
        }
        pop = next;
    }
}
"""


def generate_rust_source(params: dict) -> str:
    """パラメータ辞書から Rust ソースを生成する"""
    n = params["N_LAYERS"]
    llen = params["LAYER_LEN"]
    llen2 = params["LAYER_LEN_LAST"]
    nadf = params["N_ADF_PER_LAYER"]

    layer_len_arr = ", ".join([str(llen)] * (n - 1) + [str(llen2)])

    if n == 1:
        n_adf_arr = ""
    else:
        n_adf_arr = ", ".join([str(nadf)] * (n - 1))

    elite = params["ELITE"]
    pop_size = params["POP_SIZE"]
    elite = min(elite, pop_size // 2)
    elite = max(elite, 2)

    src = RUST_TEMPLATE.format(
        N_LAYERS=n,
        LAYER_LEN_ARR=layer_len_arr,
        N_ADF_ARR=n_adf_arr,
        VEC_LEN=params["VEC_LEN"],
        POP_SIZE=pop_size,
        ELITE=elite,
        PROB_EML=f"{params['PROB_EML']:.8f}",
        A=f"{params['A']:.8f}",
        B=f"{params['B']:.8f}",
        C=f"{params['C']:.8f}",
        D=f"{params['D']:.8f}",
        HILO=f"{params['HILO']:.8f}",
        P=f"{params['P']:.8f}",
        MUT_STOP_PROB=f"{params['MUT_STOP_PROB']:.8f}",
        MUT_MAX_TARGETS=params["MUT_MAX_TARGETS"],
        BODY=RUST_BODY,
    )
    return src


# ─── ビルド & 実行 ────────────────────────────────────────────────────────────

def build_and_run(
    params: dict,
    project_dir: str,
    eval_time: int,
    trial_idx: int,
    out_dir: str,
) -> float:
    src = generate_rust_source(params)
    src_path = os.path.join(project_dir, "src", "main.rs")

    with open(src_path, "w", encoding="utf-8") as f:
        f.write(src)

    log_dir = os.path.join(out_dir, f"trial_{trial_idx:04d}")
    os.makedirs(log_dir, exist_ok=True)

    with open(os.path.join(log_dir, "params.json"), "w") as f:
        json.dump(params, f, indent=2)

    print(f"  [trial {trial_idx}] Building ...", flush=True)
    build_start = time.time()
    build_result = subprocess.run(
        ["cargo", "build", "--release"],
        cwd=project_dir,
        capture_output=True,
        text=True,
        timeout=300,
    )
    build_elapsed = time.time() - build_start

    if build_result.returncode != 0:
        print(f"  [trial {trial_idx}] BUILD FAILED ({build_elapsed:.1f}s)")
        print(build_result.stderr[-2000:])
        with open(os.path.join(log_dir, "build_stderr.txt"), "w") as f:
            f.write(build_result.stderr)
        return 0.0

    print(f"  [trial {trial_idx}] Build OK ({build_elapsed:.1f}s). Running {eval_time}s ...", flush=True)

    cargo_toml = os.path.join(project_dir, "Cargo.toml")
    bin_name = None
    try:
        import tomllib
    except ImportError:
        tomllib = None

    if tomllib and os.path.exists(cargo_toml):
        with open(cargo_toml, "rb") as f:
            toml_data = tomllib.load(f)
        bin_name = toml_data.get("package", {}).get("name", None)
    if bin_name is None:
        if os.path.exists(cargo_toml):
            for line in open(cargo_toml):
                m = re.match(r'\s*name\s*=\s*"([^"]+)"', line)
                if m:
                    bin_name = m.group(1)
                    break
    if bin_name is None:
        bin_name = os.path.basename(project_dir)

    binary = os.path.join(project_dir, "target", "release", bin_name)

    run_proc = subprocess.Popen(
        [binary],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        cwd=project_dir,
    )

    import select as _select
    lines = []
    deadline = time.time() + eval_time
    last_output_time = time.time()
    SILENCE_TIMEOUT = 5.0
    timed_out_by_silence = False

    try:
        while time.time() < deadline:
            remaining = min(deadline - time.time(), SILENCE_TIMEOUT - (time.time() - last_output_time))
            if remaining <= 0:
                if time.time() - last_output_time >= SILENCE_TIMEOUT:
                    timed_out_by_silence = True
                break
            ready, _, _ = _select.select([run_proc.stdout], [], [], max(remaining, 0.0))
            if not ready:
                if time.time() - last_output_time >= SILENCE_TIMEOUT:
                    timed_out_by_silence = True
                    break
                continue
            line = run_proc.stdout.readline()
            if not line:
                break
            last_output_time = time.time()
            lines.append(line.rstrip())
            if "CMAES_ACC" in line:
                print(f"    {line.rstrip()}", flush=True)
    finally:
        run_proc.terminate()
        try:
            run_proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            run_proc.kill()

    with open(os.path.join(log_dir, "stdout.txt"), "w") as f:
        f.write("\n".join(lines))

    if timed_out_by_silence:
        print(f"  [trial {trial_idx}] INVALID: no output for {SILENCE_TIMEOUT:.0f}s → acc = None")
        with open(os.path.join(log_dir, "result.json"), "w") as f:
            json.dump({"acc": None, "invalid": "silence_timeout", **params}, f, indent=2)
        return None

    i = 0.0
    best_acc = 0.0
    for line in lines:
        m = re.search(r"CMAES_ACC.*acc=([0-9.]+)", line)
        if m:
            try:
                if i == 0:
                    best_acc = math.log(max(1 - float(m.group(1)), 1e-24))
                else:
                    best_acc = best_acc * 0.7 + math.log(max(1 - float(m.group(1)), 1e-24)) * 0.3
                i += 1
            except ValueError:
                pass
    best_acc = 1.0 - math.exp(best_acc)

    print(f"  [trial {trial_idx}] acc = {best_acc:.6f}")
    with open(os.path.join(log_dir, "result.json"), "w") as f:
        json.dump({"acc": best_acc, **params}, f, indent=2)

    return best_acc


# ─── CMA-ES ループ ────────────────────────────────────────────────────────────

class CMAESSearcher:
    def __init__(self, project_dir: str, eval_time: int, budget: int, out_dir: str):
        self.project_dir = project_dir
        self.eval_time = eval_time
        self.budget = budget
        self.out_dir = out_dir
        self.history: list[dict] = []
        self.trial_idx = 0

        os.makedirs(out_dir, exist_ok=True)

        x0 = initial_x()
        sigma0 = initial_sigma()

        bounds_lo = []
        bounds_hi = []
        for name, lo, hi, init, is_int, log_scale in PARAM_DEFS:
            if log_scale:
                bounds_lo.append(math.log(lo))
                bounds_hi.append(math.log(hi))
            else:
                bounds_lo.append(float(lo))
                bounds_hi.append(float(hi))

        opts = cma.CMAOptions()
        opts["bounds"] = [bounds_lo, bounds_hi]
        opts["maxfevals"] = budget
        opts["verbose"] = -9
        opts["tolx"] = 1e-4
        opts["tolfun"] = 1e-4

        self.es = cma.CMAEvolutionStrategy(x0, sigma0, opts)
        print(f"CMA-ES initialized: dim={len(x0)}, sigma0={sigma0:.3f}, budget={budget}")

    def objective(self, x: list[float]) -> float:
        params = decode(x)
        print(f"\n{'='*60}")
        print(f"Trial {self.trial_idx}: {params}")
        acc = build_and_run(params, self.project_dir, self.eval_time, self.trial_idx, self.out_dir)
        self.trial_idx += 1

        if acc is None:
            fitness = 0.0
            self.history.append({"trial": self.trial_idx - 1, "acc": None, "invalid": True, **params})
            self._save_history()
            return fitness

        EPS = 1e-24
        fitness = math.log(max(1.0 - acc, EPS))
        self.history.append({"trial": self.trial_idx - 1, "acc": acc, **params})
        self._save_history()
        return fitness

    def run(self):
        print("\n" + "="*60)
        print("Starting CMA-ES hyperparameter search")
        print("="*60)

        global_best_fitness = float("inf")
        global_best_params = None

        while not self.es.stop() and self.trial_idx < self.budget:
            solutions = self.es.ask()
            fitnesses = [self.objective(x) for x in solutions]
            self.es.tell(solutions, fitnesses)

            iter_best_idx = int(min(range(len(fitnesses)), key=lambda i: fitnesses[i]))
            iter_best_fitness = fitnesses[iter_best_idx]
            iter_best_params = decode(solutions[iter_best_idx])

            if iter_best_fitness < global_best_fitness:
                global_best_fitness = iter_best_fitness
                global_best_params = iter_best_params

            global_best_acc = 1.0 - math.exp(min(global_best_fitness, 0.0))
            iter_best_acc = 1.0 - math.exp(min(iter_best_fitness, 0.0))
            print(
                f"\n>>> iter best: acc≈{iter_best_acc:.6f} | "
                f"global best: acc≈{global_best_acc:.6f} params={global_best_params}"
            )

        print("\n" + "="*60)
        print("CMA-ES search finished.")
        if self.history:
            valid = [d for d in self.history if d.get("acc") is not None]
            if valid:
                best = max(valid, key=lambda d: d["acc"])
                print(f"Best trial #{best['trial']}: acc={best['acc']:.6f}")
                print(f"Best params: { {k: v for k, v in best.items() if k not in ('trial','acc')} }")
                with open(os.path.join(self.out_dir, "best_params.json"), "w") as f:
                    json.dump(best, f, indent=2)
                print(f"Saved to {self.out_dir}/best_params.json")
        return self.history

    def _save_history(self):
        with open(os.path.join(self.out_dir, "history.json"), "w") as f:
            json.dump(self.history, f, indent=2)


# ─── Cargo.toml テンプレート ─────────────────────────────────────────────────

CARGO_TOML_TEMPLATE = """\
[package]
name = "adf_cgp"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
dashmap = "5"
num-complex = "0.4"
rand = {{ version = "0.8", features = ["small_rng"] }}
rayon = "1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
"""


def setup_project(project_dir: str, src_rs_path: Optional[str] = None):
    src_dir = os.path.join(project_dir, "src")
    os.makedirs(src_dir, exist_ok=True)

    cargo_toml = os.path.join(project_dir, "Cargo.toml")
    if not os.path.exists(cargo_toml):
        print(f"Creating new Cargo project at {project_dir}")
        with open(cargo_toml, "w") as f:
            f.write(CARGO_TOML_TEMPLATE)

    src_dest = os.path.join(src_dir, "main.rs")
    if src_rs_path and os.path.exists(src_rs_path):
        shutil.copy2(src_rs_path, src_dest)
        print(f"Copied {src_rs_path} → {src_dest}")
    elif not os.path.exists(src_dest):
        params = {name: init for name, lo, hi, init, is_int, log_scale in PARAM_DEFS}
        with open(src_dest, "w") as f:
            f.write(generate_rust_source(params))
        print(f"Generated initial main.rs at {src_dest}")


# ─── エントリポイント ─────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="CMA-ES hyperparameter search for ADF-CGP",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
        例:
          # カレントディレクトリが Cargo プロジェクトの場合
          python3 cmaes_search.py --project . --budget 30 --time 30

          # ソースファイルを指定して新規プロジェクト作成
          python3 cmaes_search.py --project ./adf_cgp_proj --src main.rs --budget 30 --time 30
        """),
    )
    parser.add_argument("--project", default=".", help="Cargo プロジェクトのルートディレクトリ")
    parser.add_argument("--src", default=None, help="元の main.rs パス (省略時はプロジェクト内のものを使用)")
    parser.add_argument("--out", default="cmaes_results", help="結果出力ディレクトリ")
    parser.add_argument("--budget", type=int, default=DEFAULT_BUDGET, help="CMA-ES 最大評価回数")
    parser.add_argument("--time", type=int, default=DEFAULT_TIME, help="各評価の実行秒数")
    args = parser.parse_args()

    project_dir = os.path.abspath(args.project)
    out_dir = os.path.abspath(args.out)

    print(f"Project dir : {project_dir}")
    print(f"Output dir  : {out_dir}")
    print(f"Budget      : {args.budget} evaluations")
    print(f"Eval time   : {args.time} seconds each")

    setup_project(project_dir, args.src)

    searcher = CMAESSearcher(
        project_dir=project_dir,
        eval_time=args.time,
        budget=args.budget,
        out_dir=out_dir,
    )
    searcher.run()


if __name__ == "__main__":
    main()