#!/usr/bin/env python3
"""
CMA-ES によるADF-CGP ハイパーパラメータ探索 (Surrogate Model付き)
============================================

探索対象:
  - N_LAYERS       : 2〜9 (整数)
  - LAYER_LEN      : 各層共通のノード数 4〜128 (整数)
  - LAYER_LEN_LAST : 最終層ノード数 4〜1024 (整数)
  - N_ADF_PER_LAYER: 各ADF層共通のADF数 1〜32 (整数)
  - ELITE          : 8〜256 (整数)
  - POP_SIZE       : 48〜16384 (整数)
  - VEC_LEN        : 64〜16384 (整数)
  - PROB_EML       : 0.0〜1.0 (実数)
  - MUT_STOP_PROB  : 0.001〜12 (実数)
  - MUT_MAX_TARGETS: 1〜8 (整数)
  - SURR_EMBED_DIM : surrogate MLP の埋め込み次元 n (8〜256)
  - SURR_HIDDEN_DIM: surrogate MLP の隠れ次元 m (8〜512)
  - SURR_LR        : Muon Optimizer の学習率 (1e-4〜1e-1)
  - SURR_RATIO     : surrogate ステップ / 実評価ステップの比率初期値 (0.05〜20)

使い方:
  python3 cmaes_search.py [--project DIR] [--out OUT_DIR] [--budget N] [--time SEC]

依存:
  pip install cma
  cargo / rustc が PATH 上にあること
"""

import argparse
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
import textwrap
import time
from pathlib import Path
from typing import Optional

import cma

# ─── デフォルト設定 ───────────────────────────────────────────────────────────

DEFAULT_OUT     = "cmaes_results"
DEFAULT_BUDGET  = 2000
DEFAULT_TIME    = 30

# ─── ハイパーパラメータ定義 ──────────────────────────────────────────────────

PARAM_DEFS = [
    # (name,             lo,    hi,   init,  is_int, log_scale)
    ("N_LAYERS",          2,     9,    3,    True,   True),
    ("LAYER_LEN",         4,    128,   32,   True,   True),
    ("LAYER_LEN_LAST",    4,   1024,   64,   True,   True),
    ("N_ADF_PER_LAYER",   1,    32,    12,   True,   True),
    ("ELITE",             8,   256,   24,   True,   True),
    ("POP_SIZE",         48,  16384, 1024,  True,   True),
    ("VEC_LEN",          64,  16384, 1024,  True,   True),
    ("PROB_EML",        0.0,   1.0,   0.3,  False,  False),
    ("A",              -1.5,   2.0,   0.01, False,  False),
    ("B",               0.0,   1.0,   0.5,  False,  False),
    ("C",              -1.5,   2.0,   0.01, False,  False),
    ("D",               0.0,   1.0,   0.5,  False,  False),
    ("E",              -1.5,   2.0,   0.01, False,  False),
    ("HILO",             7.5,  50,   10.0,  False,  True),
    ("P",               0.5,   3,    1.5,   False,  True),
    ("MUT_STOP_PROB",   0.001, 12,    6,    False,  False),
    ("MUT_MAX_TARGETS",  1,     64,    16,   True,   True),
    # ── Surrogate Model ハイパーパラメータ ──────────────────────────────────
    # Tree-structured MLP の埋め込み次元 n
    ("SURR_EMBED_DIM",   8,   256,   32,   True,   True),
    # Tree-structured MLP の隠れ次元 m  (n*2 → m → n のボトルネック)
    ("SURR_HIDDEN_DIM",  8,   512,   64,   True,   True),
    # Muon Optimizer の学習率
    ("SURR_LR",         1e-4,  0.1,  3e-3, False,  True),
    # surrogate ステップ / 実評価ステップの比率 (初期値)
    ("SURR_RATIO",      0.05,  20.0, 1.0,  False,  True),
    ("SURR_PROMOTE_THRESH", 0.01, 0.99, 0.5, False, False),
    ("SURR_DEMOTE_RATIO",  0.01, 0.99, 0.1,  False, False),
    ("SURR_MAX_MULTIPLIER", 1.01, 50.0, 4.0,  False, False),
]

# ─── ユーティリティ ──────────────────────────────────────────────────────────

def encode(params: dict) -> list:
    vec = []
    for name, lo, hi, init, is_int, log_scale in PARAM_DEFS:
        v = params[name]
        if log_scale:
            vec.append(math.log(max(v, 1e-9)))
        else:
            vec.append(float(v))
    return vec

def decode(x: list) -> dict:
    result = {}
    for i, (name, lo, hi, init, is_int, log_scale) in enumerate(PARAM_DEFS):
        v = x[i]
        if log_scale:
            v = math.exp(v)
        v = max(lo, min(hi, v))
        if is_int:
            v = int(round(v))
            v = max(int(lo), min(int(hi), v))
        result[name] = v
    return result

def initial_x() -> list:
    params = {name: init for name, lo, hi, init, is_int, log_scale in PARAM_DEFS}
    return encode(params)

def initial_sigma() -> float:
    return 6.0

# ─── Rustソース生成 ──────────────────────────────────────────────────────────

RUST_TEMPLATE = """\
// AUTO-GENERATED by cmaes_search.py — DO NOT EDIT
use ahash::AHasher;
use dashmap::DashMap;
use ndarray::{{Array1, Array2, Axis}};
use num_complex::Complex;
use rand::rngs::SmallRng;
use rand::{{Rng, SeedableRng}};
use rayon::prelude::*;
use std::hash::{{Hash, Hasher}};
use std::sync::Arc;

// ─── アーキテクチャ ハイパーパラメータ ───────────────────────────────────────
const N_LAYERS: usize = {N_LAYERS};
const LAYER_LEN: [usize; N_LAYERS] = [{LAYER_LEN_ARR}];
const N_INPUTS_MAIN: usize = 2;
const N_INPUTS_ADF: usize = 4;
const N_ADF_PER_LAYER: [usize; N_LAYERS - 1] = [{N_ADF_ARR}];
const ONE_SIG: Sig = 0xFFFF_FFFF_FFFF_FFFFu64;
const X_GLOBAL_SIG_SLOT: usize = 3;
const VEC_LEN: usize = {VEC_LEN};
const POP_SIZE: usize = {POP_SIZE};
const ELITE: usize = {ELITE};
const N_GEN: usize = 99999999;
const PROB_EML: f64 = {PROB_EML};
const A: f64 = {A};
const B: f64 = {B};
const C: f64 = {C};
const D: f64 = {D};
const E: f64 = {E};
const HILO: f64 = {HILO};
const P: f64 = {P};
const MUT_STOP_PROB: f64 = {MUT_STOP_PROB};
const MUT_MAX_TARGETS: usize = {MUT_MAX_TARGETS};

// ─── Surrogate Model ハイパーパラメータ ─────────────────────────────────────
/// Tree-structured MLP の埋め込み次元 n
const SURR_EMBED_DIM: usize = {SURR_EMBED_DIM};
/// Tree-structured MLP の隠れ次元 m  (n*2 → Linear → m → Swish → Linear → n)
const SURR_HIDDEN_DIM: usize = {SURR_HIDDEN_DIM};
/// Muon Optimizer の学習率
const SURR_LR: f64 = {SURR_LR};
/// surrogate ステップ / 実評価ステップの比率 (初期値)
const SURR_RATIO_INIT: f64 = {SURR_RATIO};
/// surrogate のバリデーション相関がこの値を超えたら surrogate ステップ倍率を上げる
const SURR_PROMOTE_THRESH: f64 = {SURR_PROMOTE_THRESH};
/// surrogate のバリデーション相関がこの値を下回ったら surrogate ステップ倍率を下げる
const SURR_DEMOTE_THRESH: f64 = {SURR_DEMOTE_THRESH};
/// surrogate ステップ数の最大倍率 (SURR_RATIO_INIT に対する乗数上限)
const SURR_MAX_MULTIPLIER: f64 = {SURR_MAX_MULTIPLIER};

// ─── カリキュラム学習 ────────────────────────────────────────────────────────
const CURRICULUM_RAMP_GENS: usize = 1;
const INTER_WEIGHT_MAX: f64 = 1.0;
const ADF_CACHE_MAX: usize = 1 << 18;
const N_BATCHES: usize = 1;

{BODY}
"""

RUST_BODY = r"""
// ─── レイヤー設定ヘルパー ─────────────────────────────────────────────────────

#[inline] fn is_top(layer_idx: usize) -> bool { layer_idx == N_LAYERS - 1 }
#[inline] fn layer_len(layer_idx: usize) -> usize { LAYER_LEN[layer_idx] }
#[inline] fn layer_n_ext(layer_idx: usize) -> usize { if is_top(layer_idx) { N_INPUTS_MAIN } else { N_INPUTS_ADF } }
#[inline] fn layer_n_adf(layer_idx: usize) -> usize { N_ADF_PER_LAYER[layer_idx] }
#[inline] fn layer_n_funcs(layer_idx: usize) -> usize { if layer_idx == 0 { 1 } else { 1 + layer_n_adf(layer_idx - 1) } }

fn selectfunc(max: u8, rng: &mut SmallRng) -> u8 {
    if rng.gen::<f64>() < PROB_EML { return 0; }
    rng.gen_range(0..max)
}

// ─── 複素数ユーティリティ ─────────────────────────────────────────────────────

#[inline(always)]
fn clamp(z: Complex<f64>) -> Complex<f64> {
    const M: f64 = 15.0;
    Complex::new(z.re.clamp(-M, M), z.im.clamp(-M, M))
}
#[inline(always)]
fn safe_log(z: Complex<f64>) -> Complex<f64> {
    const EPS: f64 = 1e-6;
    if z.norm_sqr() < EPS * EPS { Complex::new(EPS, 0.0).ln() } else { z.ln() }
}
#[inline(always)]
fn eml(a: Complex<f64>, b: Complex<f64>) -> Complex<f64> {
    clamp(a).exp() - safe_log(b)
}
fn eml_vec(x: &[Complex<f64>], y: &[Complex<f64>]) -> Vec<Complex<f64>> {
    x.iter().zip(y).map(|(&a, &b)| eml(a, b)).collect()
}

// ─── Chromosome ───────────────────────────────────────────────────────────────

#[derive(Clone)]
struct Chromosome {
    layer_idx: usize,
    conn: Box<[[u16; 2]]>,
    func: Box<[u8]>,
}

impl Chromosome {
    fn random(layer_idx: usize, rng: &mut SmallRng) -> Self {
        let n = layer_len(layer_idx);
        let n_ext = layer_n_ext(layer_idx);
        let n_f = layer_n_funcs(layer_idx) as u8;
        let conn = (0..n)
            .map(|i| { let m = (n_ext + i) as u16; [((1.0 - rng.gen::<f64>().powf(P)) * m as f64).floor() as u16, ((1.0 - rng.gen::<f64>().powf(P)) * m as f64).floor() as u16] })
            .collect::<Vec<_>>().into_boxed_slice();
        let func = (0..n).map(|_| selectfunc(n_f, rng)).collect::<Vec<_>>().into_boxed_slice();
        Self { layer_idx, conn, func }
    }

    fn active_and_sig(&self) -> (Vec<usize>, u64) {
        let n = layer_len(self.layer_idx);
        let n_ext = layer_n_ext(self.layer_idx);
        let total = n_ext + n;
        let mut active = vec![false; total];
        active[total - 1] = true;
        for i in (0..n).rev() {
            if !active[n_ext + i] { continue; }
            active[self.conn[i][0] as usize] = true;
            active[self.conn[i][1] as usize] = true;
        }
        let mut h = AHasher::default();
        (self.layer_idx as u8).hash(&mut h);
        let list: Vec<usize> = (0..total).filter(|&i| active[i])
            .inspect(|&abs| {
                if abs >= n_ext {
                    let i = abs - n_ext;
                    self.conn[i][0].hash(&mut h); self.conn[i][1].hash(&mut h);
                    self.func[i].hash(&mut h); abs.hash(&mut h);
                }
            }).collect();
        (list, h.finish())
    }

    fn mutate(&self, rng: &mut SmallRng) -> Self {
        let mut conn = self.conn.to_vec();
        let mut func = self.func.to_vec();
        let n = layer_len(self.layer_idx);
        let n_ext = layer_n_ext(self.layer_idx);
        let n_f = layer_n_funcs(self.layer_idx) as u8;
        let n_mut = (rng.gen::<f64>() * MUT_STOP_PROB).exp() as usize + 1;
        for _ in 0..n_mut {
            let i = rng.gen_range(0..n);
            let max = (n_ext + i) as u16;
            match rng.gen_range(0..3u8) {
                0 => conn[i][0] = ((1.0 - rng.gen::<f64>().powf(P)) * max as f64).floor() as u16,
                1 => conn[i][1] = ((1.0 - rng.gen::<f64>().powf(P)) * max as f64).floor() as u16,
                _ => func[i] = selectfunc(n_f, rng),
            }
            if rng.gen::<f64>() < 0.05 {
                conn[i][rng.gen_range(0..2)] = rng.gen_range(0..n_ext as u16);
            }
        }
        Self { layer_idx: self.layer_idx, conn: conn.into_boxed_slice(), func: func.into_boxed_slice() }
    }

    fn mix(&self, rng: &mut SmallRng, other: &Chromosome) -> Self {
        let (active2, _) = other.active_and_sig();
        let n_ext = layer_n_ext(self.layer_idx);
        let mut conn = self.conn.to_vec();
        let mut func = self.func.to_vec();
        let mut cands: Vec<usize> = active2.into_iter().filter(|&i| i >= n_ext).collect();
        if !cands.is_empty() {
            let n_copy = rng.gen_range(1..=cands.len());
            for i in 0..n_copy.min(cands.len()) {
                let j = rng.gen_range(i..cands.len());
                cands.swap(i, j);
                let local = cands[i] - n_ext;
                conn[local] = other.conn[local];
                func[local] = other.func[local];
            }
        }
        Self { layer_idx: self.layer_idx, conn: conn.into_boxed_slice(), func: func.into_boxed_slice() }
    }
}

// ─── Genome ───────────────────────────────────────────────────────────────────

#[derive(Clone)]
struct Genome { layers: Vec<Vec<Chromosome>> }

impl Genome {
    fn random(rng: &mut SmallRng) -> Self {
        let layers = (0..N_LAYERS).map(|li| {
            let count = if is_top(li) { 1 } else { layer_n_adf(li) };
            (0..count).map(|_| Chromosome::random(li, rng)).collect()
        }).collect();
        Self { layers }
    }

    fn mutate(&self, rng: &mut SmallRng) -> Self {
        let mut g = self.clone();
        let totals: Vec<usize> = (0..N_LAYERS)
            .map(|li| if is_top(li) { 1 } else { layer_n_adf(li) }).collect();
        let grand_total: usize = totals.iter().sum();
        let n_targets = rng.gen_range(1..=MUT_MAX_TARGETS.min(grand_total));
        for _ in 0..n_targets {
            let mut t = rng.gen_range(0..grand_total);
            for (li, &cnt) in totals.iter().enumerate() {
                if t < cnt { g.layers[li][t] = self.layers[li][t].mutate(rng); break; }
                t -= cnt;
            }
        }
        g
    }

    fn mix(&self, rng: &mut SmallRng, other: &Genome) -> Self {
        let mut g = self.clone();
        for li in 0..N_LAYERS {
            let cnt = if is_top(li) { 1 } else { layer_n_adf(li) };
            for k in 0..cnt {
                if rng.gen::<f64>() < 0.5 {
                    g.layers[li][k] = self.layers[li][k].mix(rng, &other.layers[li][k]);
                }
            }
        }
        g
    }
}

// ─── Signature ────────────────────────────────────────────────────────────────

type Sig = u64;

#[inline]
fn make_sig(a: Sig, b: Sig, func_id: u8) -> Sig {
    let mut x = a ^ ((func_id as u64).wrapping_mul(0x9e3779b97f4a7c15));
    x ^= b.wrapping_mul(0x6c62272e07bb0142);
    x ^= x >> 30; x = x.wrapping_mul(0xbf58476d1ce4e5b9);
    x ^= x >> 27; x = x.wrapping_mul(0x94d049bb133111eb);
    x ^ (x >> 31)
}

fn genome_key(all_sigs: &[Vec<Sig>]) -> u64 {
    let mut h = AHasher::default();
    for layer_sigs in all_sigs { for &s in layer_sigs { s.hash(&mut h); } }
    h.finish()
}

// ─── Cache ────────────────────────────────────────────────────────────────────

type ArcVec = Arc<[Complex<f64>]>;
type AdfKey = (Sig, Sig, Sig, Sig, Sig);
type Score = (f64, f64);

struct NodeBuf { sigs: Vec<Sig>, vals: Vec<ArcVec> }

impl NodeBuf {
    fn new(total: usize) -> Self {
        let dummy: ArcVec = Arc::from(vec![Complex::new(0.0, 0.0); VEC_LEN].into_boxed_slice());
        Self { sigs: vec![0u64; total], vals: vec![dummy; total] }
    }
    #[inline] fn set(&mut self, idx: usize, sig: Sig, val: ArcVec) { self.sigs[idx] = sig; self.vals[idx] = val; }
    #[inline] fn sig(&self, idx: usize) -> Sig { self.sigs[idx] }
    #[inline] fn val(&self, idx: usize) -> &ArcVec { &self.vals[idx] }
}

#[inline]
fn node_get_or_compute(sig: Sig, v0: &[Complex<f64>], v1: &[Complex<f64>], ev: &Evaluator) -> ArcVec {
    if let Some(v) = ev.node_cache.get(&sig) { return Arc::clone(&*v); }
    let out: ArcVec = Arc::from(eml_vec(v0, v1).into_boxed_slice());
    ev.node_cache.entry(sig).or_insert_with(|| Arc::clone(&out));
    out
}

// ─── Dataset ──────────────────────────────────────────────────────────────────

fn target_fn(x: Complex<f64>) -> Complex<f64> { (x * x * x - x).sin() * (x * x).sin() }

fn make_batch(rng: &mut SmallRng, x_range: (f64, f64))
    -> ([Vec<Complex<f64>>; N_INPUTS_MAIN], Vec<Complex<f64>>)
{
    let (lo, hi) = x_range;
    let xs: Vec<Complex<f64>> = (0..VEC_LEN)
        .map(|_| Complex::new(lo + rng.gen::<f64>() * (hi - lo), 0.0)).collect();
    let one = vec![Complex::new(1.0, 0.0); VEC_LEN];
    let ys = xs.iter().map(|&x| target_fn(x)).collect();
    ([xs, one], ys)
}

struct Dataset {
    batches: Vec<([Vec<Complex<f64>>; N_INPUTS_MAIN], Vec<Complex<f64>>)>,
    batch_sig: Sig,
}

impl Dataset {
    fn new_fixed(rng: &mut SmallRng) -> Self {
        let batches: Vec<_> = (0..N_BATCHES).map(|_| make_batch(rng, (-HILO, HILO))).collect();
        let batch_sig = Self::compute_sig(&batches);
        Self { batches, batch_sig }
    }
    fn compute_sig(batches: &[([Vec<Complex<f64>>; N_INPUTS_MAIN], Vec<Complex<f64>>)]) -> Sig {
        let mut h = AHasher::default();
        for (inputs, _) in batches { for z in inputs[0].iter().take(8) { z.re.to_bits().hash(&mut h); } }
        h.finish()
    }
}

// ─── Surrogate Model ─────────────────────────────────────────────────────────
//
// 設計:
//   各ゲノムノードで h = MLP(h_left, h_right) を計算（h は SURR_EMBED_DIM 次元）
//   MLP: [2*n] → Linear(2n→m) → Swish → Linear(m→n)
//   leaf（ext入力スロット）の埋め込みは学習対象ベクトル
//   最終ノードの埋め込み h_out → Linear(n→1) で loss を予測
//
// 最適化のポイント:
//   1. ForwardCache を導入し、フォワードパスを1回だけ走査して中間値を保存。
//      genome_backward はこのキャッシュを受け取って再走査を完全に排除する。
//   2. surrogate_predict は precomputed な GenomeData を受け取るオーバーロードを追加し、
//      呼び出し元（surrogate評価フェーズ）で active_and_sig を1回だけ計算する。
//   3. embed_cache は HashMap<Sig, Array1<f64>> として世代をまたいで保持し、
//      重み更新後のみクリアする（同一世代内の共通サブツリーを再利用）。
//   4. update_val_correlation でも precomputed GenomeData を使用する。

/// Swish 活性化関数: x * sigmoid(x)
#[inline]
fn swish(x: f64) -> f64 { x / (1.0 + (-x).exp()) }

/// Swish の微分: sigmoid(x) + x * sigmoid(x) * (1 - sigmoid(x))
#[inline]
fn swish_grad(x: f64) -> f64 {
    let s = 1.0 / (1.0 + (-x).exp());
    s + x * s * (1.0 - s)
}

/// Muon で採用されている5次Newton-Schulz反復を用いた直交化
fn newton_schulz_orthogonalize(g: &Array2<f64>, steps: usize) -> Array2<f64> {
    let (rows, cols) = g.dim();
    if rows == 0 || cols == 0 { return g.clone(); }
    let norm = g.iter().map(|x| x * x).sum::<f64>().sqrt().max(1e-10);
    let mut x = g / norm;
    let (a, b, c) = (3.4445, -4.7750, 2.0315);
    for _ in 0..steps {
        let xt = x.t();
        let s = xt.dot(&x);
        let s2 = s.dot(&s);
        let eye = Array2::<f64>::eye(cols);
        let mut m = eye * a;
        m += &(&s * b);
        m += &(&s2 * c);
        x = x.dot(&m);
    }
    x
}

// ─── ノードSig計算（全構造情報を含む・衝突なし）────────────────────────────

fn compute_node_sig_recursive(
    abs: usize,
    layer_idx: usize,
    c: &Chromosome,
    node_sigs: &[Sig],
    all_sigs: &[Vec<Sig>],
    n_ext: usize,
) -> Sig {
    if abs < n_ext {
        return abs as Sig + 1;
    }
    let i = abs - n_ext;
    let c0 = c.conn[i][0] as usize;
    let c1 = c.conn[i][1] as usize;
    let f = c.func[i] as usize;
    let s0 = node_sigs[c0];
    let s1 = node_sigs[c1];
    if f == 0 || layer_idx == 0 {
        make_sig(s0, s1, 0)
    } else {
        let sub_li = layer_idx - 1;
        let sub_idx = (f - 1).min(layer_n_adf(sub_li) - 1);
        let adf_sig = all_sigs[sub_li][sub_idx];
        make_sig(make_sig(s0, s1, f as u8), adf_sig, 0)
    }
}

// ─── ゲノムの事前計算済みデータ ──────────────────────────────────────────────
//
// active_and_sig の結果をキャッシュし、surrogate 評価フェーズ全体で再利用する。
// これにより POP_SIZE 回の重複計算を排除する。

struct GenomeData {
    all_sigs: Vec<Vec<Sig>>,
    all_acts: Vec<Vec<Vec<usize>>>,
    genome_key: u64,
}

impl GenomeData {
    fn new(genome: &Genome) -> Self {
        let all_data: Vec<Vec<(Vec<usize>, Sig)>> = (0..N_LAYERS)
            .map(|li| genome.layers[li].iter().map(|c| c.active_and_sig()).collect())
            .collect();
        let all_sigs: Vec<Vec<Sig>> = all_data.iter()
            .map(|layer| layer.iter().map(|d| d.1).collect()).collect();
        let all_acts: Vec<Vec<Vec<usize>>> = all_data.into_iter()
            .map(|layer| layer.into_iter().map(|d| d.0).collect()).collect();
        let gk = genome_key(&all_sigs);
        Self { all_sigs, all_acts, genome_key: gk }
    }
}

// ─── フォワードパスの中間値キャッシュ ────────────────────────────────────────
//
// フォワードパスで計算した中間値をすべて保持する。
// backward はこのキャッシュを受け取り、再走査を行わない。

struct NodeFwdEntry {
    node_sig:   Sig,
    concat_inp: Array1<f64>,  // [2n] 連結入力
    pre_swish:  Array1<f64>,  // Linear(2n→m) の出力（Swish前）
    h_out:      Array1<f64>,  // Linear(m→n) の出力（このノードの埋め込み）
    c0:         usize,
    c1:         usize,
}

/// フォワードパスの全中間値: fwd_entries[li][k][abs] = Option<NodeFwdEntry>
/// ext スロットの埋め込みは ext_embeds[li][k][i] に格納
struct ForwardCache {
    // [li][k][abs] = Some(entry) for internal nodes, None for ext slots
    fwd_entries: Vec<Vec<Vec<Option<NodeFwdEntry>>>>,
    // [li][k][i] = embedding for ext slot i
    ext_embeds:  Vec<Vec<Vec<Array1<f64>>>>,
    // [li][k][abs] = node_sig (0 if not computed)
    node_sigs:   Vec<Vec<Vec<Sig>>>,
    // top layer output embedding (= last node of top chrom)
    top_embed:   Array1<f64>,
}

// ─── Surrogate Model の重みとモメンタム ─────────────────────────────────────

struct SurrogateWeights {
    // leaf embeddings: ext スロット Sig → SURR_EMBED_DIM ベクトル
    leaf_embeds: std::collections::HashMap<u64, Array1<f64>>,

    // MLP ノード層: [2*n → m] の重みと偏り
    w1: Array2<f64>, // (SURR_HIDDEN_DIM, 2*SURR_EMBED_DIM)
    b1: Array1<f64>, // (SURR_HIDDEN_DIM,)
    // [m → n] の重みと偏り
    w2: Array2<f64>, // (SURR_EMBED_DIM, SURR_HIDDEN_DIM)
    b2: Array1<f64>, // (SURR_EMBED_DIM,)
    // 最終スカラー予測層: [n → 1]
    w_out: Array1<f64>, // (SURR_EMBED_DIM,)
    b_out: f64,

    // Muon モメンタム（各重み行列対応）
    m_w1: Array2<f64>,
    m_b1: Array1<f64>,
    m_w2: Array2<f64>,
    m_b2: Array1<f64>,
    m_w_out: Array1<f64>,
    m_b_out: f64,
    // leaf embedding モメンタム
    m_leaf: std::collections::HashMap<u64, Array1<f64>>,

    // ハイパーパラメータ
    lr: f64,
    momentum: f64,

    // バリデーション用 held-out バッファ
    held_out_buffer: Vec<(u64, f64, Genome)>,
    val_correlation: f64,
    surrogate_multiplier: f64,
}

impl SurrogateWeights {
    fn new(lr: f64) -> Self {
        use rand::SeedableRng;
        let mut rng = SmallRng::seed_from_u64(12345);
        let n = SURR_EMBED_DIM;
        let m = SURR_HIDDEN_DIM;
        let scale1 = (2.0 / (2 * n) as f64).sqrt();
        let scale2 = (2.0 / m as f64).sqrt();
        let rand_mat = |rows: usize, cols: usize, scale: f64, rng: &mut SmallRng| -> Array2<f64> {
            Array2::from_shape_fn((rows, cols), |_| (rng.gen::<f64>() * 2.0 - 1.0) * scale)
        };
        let rand_vec = |size: usize, scale: f64, rng: &mut SmallRng| -> Array1<f64> {
            Array1::from_shape_fn(size, |_| (rng.gen::<f64>() * 2.0 - 1.0) * scale)
        };
        Self {
            leaf_embeds: std::collections::HashMap::new(),
            w1: rand_mat(m, 2 * n, scale1, &mut rng),
            b1: Array1::zeros(m),
            w2: rand_mat(n, m, scale2, &mut rng),
            b2: Array1::zeros(n),
            w_out: rand_vec(n, (2.0 / n as f64).sqrt(), &mut rng),
            b_out: 0.0,
            m_w1: Array2::zeros((m, 2 * n)),
            m_b1: Array1::zeros(m),
            m_w2: Array2::zeros((n, m)),
            m_b2: Array1::zeros(n),
            m_w_out: Array1::zeros(n),
            m_b_out: 0.0,
            m_leaf: std::collections::HashMap::new(),
            lr,
            momentum: 0.95,
            held_out_buffer: Vec::new(),
            val_correlation: 0.0,
            surrogate_multiplier: 1.0,
        }
    }

    /// leaf embedding を取得（なければ決定論的初期化）
    /// 呼び出しごとに clone しているが、ext スロット数は少ないため許容範囲。
    fn get_or_init_leaf(&mut self, sig: u64) -> Array1<f64> {
        if !self.leaf_embeds.contains_key(&sig) {
            let scale = (1.0 / SURR_EMBED_DIM as f64).sqrt();
            let embed: Array1<f64> = Array1::from_shape_fn(SURR_EMBED_DIM, |idx| {
                let h = sig
                    .wrapping_mul(0x9e3779b97f4a7c15_u64)
                    .wrapping_add(idx as u64 * 0x6c62272e07bb0142_u64);
                let h2 = h ^ (h >> 30);
                let h3 = h2.wrapping_mul(0xbf58476d1ce4e5b9_u64);
                let bits = h3 ^ (h3 >> 27);
                let frac = (bits >> 11) as f64 / (1u64 << 53) as f64;
                (frac * 2.0 - 1.0) * scale
            });
            self.leaf_embeds.insert(sig, embed);
            self.m_leaf.entry(sig).or_insert_with(|| Array1::zeros(SURR_EMBED_DIM));
        }
        self.leaf_embeds[&sig].clone()
    }

    /// MLP フォワードパス: (h_left, h_right) → (concat_input, pre_swish, h_out)
    /// 中間値をすべて返すことで、呼び出し元が backward に必要な情報を保持できる。
    #[inline]
    fn mlp_forward(&self, h_left: &Array1<f64>, h_right: &Array1<f64>)
        -> (Array1<f64>, Array1<f64>, Array1<f64>)
    {
        let mut input = Array1::zeros(2 * SURR_EMBED_DIM);
        input.slice_mut(ndarray::s![..SURR_EMBED_DIM]).assign(h_left);
        input.slice_mut(ndarray::s![SURR_EMBED_DIM..]).assign(h_right);
        let pre1 = self.w1.dot(&input) + &self.b1;
        let act1: Array1<f64> = pre1.mapv(swish);
        let out = self.w2.dot(&act1) + &self.b2;
        (input, pre1, out)
    }

    /// 最終スカラー予測: h_out → loss_pred
    #[inline]
    fn predict_from_embed(&self, h: &Array1<f64>) -> f64 {
        self.w_out.dot(h) + self.b_out
    }
}

// ─── フォワードパス（中間値キャッシュを生成） ────────────────────────────────
//
// 改善点:
//   - embed_cache ヒット時でも NodeFwdEntry を作らず、h_out だけ保存することで
//     backward が必要な場合のみフルエントリを作る。
//   - 戻り値として ForwardCache を返し、backward が再利用できるようにする。
//   - top層最終ノードの埋め込みも ForwardCache に含める。

fn genome_forward_with_cache(
    genome: &Genome,
    data: &GenomeData,
    sw: &mut SurrogateWeights,
    embed_cache: &mut std::collections::HashMap<Sig, Array1<f64>>,
    need_backward_cache: bool,  // true なら NodeFwdEntry を構築する
) -> ForwardCache {
    let mut fwd_entries: Vec<Vec<Vec<Option<NodeFwdEntry>>>> = (0..N_LAYERS).map(|li| {
        (0..genome.layers[li].len()).map(|_k| {
            vec![None; layer_n_ext(li) + layer_len(li)]
        }).collect()
    }).collect();
    let mut ext_embeds_all: Vec<Vec<Vec<Array1<f64>>>> = (0..N_LAYERS).map(|li| {
        (0..genome.layers[li].len()).map(|_k| {
            vec![Array1::zeros(SURR_EMBED_DIM); layer_n_ext(li)]
        }).collect()
    }).collect();
    let mut node_sigs_all: Vec<Vec<Vec<Sig>>> = (0..N_LAYERS).map(|li| {
        (0..genome.layers[li].len()).map(|_k| {
            vec![0u64; layer_n_ext(li) + layer_len(li)]
        }).collect()
    }).collect();

    // 各層の各 Chromosome の出力埋め込み（次の層への入力として使用）
    let mut chrom_out_embeds: Vec<Vec<Array1<f64>>> = Vec::with_capacity(N_LAYERS);

    for li in 0..N_LAYERS {
        let n_chroms = genome.layers[li].len();
        let mut layer_outs = Vec::with_capacity(n_chroms);
        for k in 0..n_chroms {
            let c = &genome.layers[li][k];
            let active = &data.all_acts[li][k];
            let n_ext = layer_n_ext(li);
            let total = n_ext + layer_len(li);

            // ext スロット初期化（leaf_embeds から取得）
            for i in 0..n_ext {
                let sig = i as Sig + 1;
                node_sigs_all[li][k][i] = sig;
                let emb = sw.get_or_init_leaf(sig);
                ext_embeds_all[li][k][i] = emb;
            }

            // active ノードをボトムアップに処理
            // node_embeds[abs] = 計算済み埋め込み（ext スロットは ext_embeds から参照）
            let mut node_embeds: Vec<Option<Array1<f64>>> = vec![None; total];
            for i in 0..n_ext {
                node_embeds[i] = Some(ext_embeds_all[li][k][i].clone());
            }

            for &abs in active {
                if abs < n_ext { continue; }

                let node_sig = compute_node_sig_recursive(
                    abs, li, c, &node_sigs_all[li][k], &data.all_sigs, n_ext,
                );
                node_sigs_all[li][k][abs] = node_sig;

                let i = abs - n_ext;
                let c0 = c.conn[i][0] as usize;
                let c1 = c.conn[i][1] as usize;

                // embed_cache ヒット: backward が不要なら NodeFwdEntry は作らない
                if let Some(cached) = embed_cache.get(&node_sig) {
                    node_embeds[abs] = Some(cached.clone());
                    if need_backward_cache {
                        // backward のために NodeFwdEntry を構築する
                        // （中間値は再計算するが、embed_cache にヒットした場合のみ）
                        let h_left  = node_embeds[c0].as_ref().map(|v| v.clone()).unwrap_or_else(|| Array1::zeros(SURR_EMBED_DIM));
                        let h_right = node_embeds[c1].as_ref().map(|v| v.clone()).unwrap_or_else(|| Array1::zeros(SURR_EMBED_DIM));
                        let (inp, pre1, _) = sw.mlp_forward(&h_left, &h_right);
                        fwd_entries[li][k][abs] = Some(NodeFwdEntry {
                            node_sig, concat_inp: inp, pre_swish: pre1,
                            h_out: cached.clone(), c0, c1,
                        });
                    }
                    continue;
                }

                let h_left  = node_embeds[c0].as_ref().map(|v| v.clone()).unwrap_or_else(|| Array1::zeros(SURR_EMBED_DIM));
                let h_right = node_embeds[c1].as_ref().map(|v| v.clone()).unwrap_or_else(|| Array1::zeros(SURR_EMBED_DIM));
                let (inp, pre1, h_out) = sw.mlp_forward(&h_left, &h_right);
                embed_cache.insert(node_sig, h_out.clone());
                node_embeds[abs] = Some(h_out.clone());

                if need_backward_cache {
                    fwd_entries[li][k][abs] = Some(NodeFwdEntry {
                        node_sig, concat_inp: inp, pre_swish: pre1,
                        h_out, c0, c1,
                    });
                }
            }

            let out = node_embeds[total - 1].clone().unwrap_or_else(|| Array1::zeros(SURR_EMBED_DIM));
            layer_outs.push(out);
        }
        chrom_out_embeds.push(layer_outs);
    }

    let top_embed = chrom_out_embeds[N_LAYERS - 1][0].clone();
    ForwardCache { fwd_entries, ext_embeds: ext_embeds_all, node_sigs: node_sigs_all, top_embed }
}

// ─── バックワード（ForwardCache を受け取り再走査なし）────────────────────────
//
// 改善点:
//   - genome_forward_with_cache の ForwardCache を受け取るため、フォワードの再走査が不要。
//   - d_node を Option<Array1> ではなく Array1 の Vec で管理し、
//     初期化済みかどうかは別の bool 配列で管理する（clone/unwrap を削減）。

fn genome_backward_from_cache(
    genome: &Genome,
    data: &GenomeData,
    fwd: &ForwardCache,
    sw: &SurrogateWeights,
    d_out_top: &Array1<f64>,
    dw1_acc: &mut Array2<f64>,
    db1_acc: &mut Array1<f64>,
    dw2_acc: &mut Array2<f64>,
    db2_acc: &mut Array1<f64>,
    d_leaf_acc: &mut std::collections::HashMap<u64, Array1<f64>>,
) {
    // d_node[li][k][abs]: そのノードへの勾配（ゼロ初期化）
    // d_node_active[li][k][abs]: 勾配が書き込まれたか
    let mut d_node: Vec<Vec<Vec<Array1<f64>>>> = (0..N_LAYERS).map(|li| {
        (0..genome.layers[li].len()).map(|_k| {
            let total = layer_n_ext(li) + layer_len(li);
            vec![Array1::zeros(SURR_EMBED_DIM); total]
        }).collect()
    }).collect();
    let mut d_node_active: Vec<Vec<Vec<bool>>> = (0..N_LAYERS).map(|li| {
        (0..genome.layers[li].len()).map(|_k| {
            let total = layer_n_ext(li) + layer_len(li);
            vec![false; total]
        }).collect()
    }).collect();

    // top 層最終ノードへの勾配を設定
    {
        let top_li = N_LAYERS - 1;
        let total_top = layer_n_ext(top_li) + layer_len(top_li);
        d_node[top_li][0][total_top - 1] = d_out_top.clone();
        d_node_active[top_li][0][total_top - 1] = true;
    }

    for li in (0..N_LAYERS).rev() {
        for k in 0..genome.layers[li].len() {
            let c = &genome.layers[li][k];
            let active = &data.all_acts[li][k];
            let n_ext = layer_n_ext(li);

            for &abs in active.iter().rev() {
                if abs < n_ext { continue; }
                if !d_node_active[li][k][abs] { continue; }

                let fw = match &fwd.fwd_entries[li][k][abs] {
                    Some(f) => f,
                    None => continue,
                };
                let c0 = fw.c0;
                let c1 = fw.c1;

                // d_out を一時コピー（後で d_node[li][k][abs] を書き換えるため）
                let d_out = d_node[li][k][abs].clone();

                // Linear(m→n) バックワード
                let act1: Array1<f64> = fw.pre_swish.mapv(swish);
                let d_act1 = sw.w2.t().dot(&d_out);
                for r in 0..SURR_EMBED_DIM {
                    for col in 0..SURR_HIDDEN_DIM {
                        dw2_acc[[r, col]] += d_out[r] * act1[col];
                    }
                }
                *db2_acc += &d_out;

                // Swish バックワード
                let d_pre1: Array1<f64> = d_act1 * fw.pre_swish.mapv(swish_grad);

                // Linear(2n→m) バックワード
                let d_inp = sw.w1.t().dot(&d_pre1);
                for r in 0..SURR_HIDDEN_DIM {
                    for col in 0..2*SURR_EMBED_DIM {
                        dw1_acc[[r, col]] += d_pre1[r] * fw.concat_inp[col];
                    }
                }
                *db1_acc += &d_pre1;

                let d_left  = d_inp.slice(ndarray::s![..SURR_EMBED_DIM]).to_owned();
                let d_right = d_inp.slice(ndarray::s![SURR_EMBED_DIM..]).to_owned();

                // c0 への勾配の伝播
                if c0 < n_ext {
                    let sig = fwd.node_sigs[li][k][c0];
                    let e = d_leaf_acc.entry(sig).or_insert_with(|| Array1::zeros(SURR_EMBED_DIM));
                    *e += &d_left;
                } else {
                    d_node[li][k][c0] += &d_left;
                    d_node_active[li][k][c0] = true;
                }

                // c1 への勾配の伝播
                if c1 < n_ext {
                    let sig = fwd.node_sigs[li][k][c1];
                    let e = d_leaf_acc.entry(sig).or_insert_with(|| Array1::zeros(SURR_EMBED_DIM));
                    *e += &d_right;
                } else {
                    d_node[li][k][c1] += &d_right;
                    d_node_active[li][k][c1] = true;
                }

                // ADF 呼び出しノードの場合、参照先 ADF Chromosome の出力ノードにも勾配を流す
                let f = c.func[abs - n_ext] as usize;
                if f != 0 && li > 0 {
                    let sub_li = li - 1;
                    let sub_idx = (f - 1).min(layer_n_adf(sub_li) - 1);
                    let sub_total = layer_n_ext(sub_li) + layer_len(sub_li);
                    d_node[sub_li][sub_idx][sub_total - 1] += &d_out;
                    d_node_active[sub_li][sub_idx][sub_total - 1] = true;
                }
            }

            // ext スロットへの勾配を d_leaf_acc に集約
            for i in 0..n_ext {
                if d_node_active[li][k][i] {
                    let sig = fwd.node_sigs[li][k][i];
                    let e = d_leaf_acc.entry(sig).or_insert_with(|| Array1::zeros(SURR_EMBED_DIM));
                    *e += &d_node[li][k][i];
                }
            }
        }
    }
}

// ─── 訓練ステップ（フォワード1回 + バックワード1回）─────────────────────────
//
// 改善点:
//   - genome_forward_with_cache(need_backward_cache=true) でフォワードを1回走査し
//     ForwardCache を生成。
//   - genome_backward_from_cache でそのキャッシュを使ってバックワードを実行。
//   - フォワードの再走査を完全に排除。
//   - embed_cache は Muon 更新後にクリアする（重みが変わったため）。

fn surrogate_train_step(
    sw: &mut SurrogateWeights,
    genome: &Genome,
    data: &GenomeData,
    actual_loss: f64,
    embed_cache: &mut std::collections::HashMap<Sig, Array1<f64>>,
) -> f64 {
    // ─── フォワード（中間値キャッシュ付き）──────────────────────────────────
    let fwd = genome_forward_with_cache(genome, data, sw, embed_cache, true);
    let pred = sw.predict_from_embed(&fwd.top_embed);
    let err = pred - actual_loss;
    let mse = err * err;

    // ─── 出力層への勾配 ──────────────────────────────────────────────────
    let d_h_final = &sw.w_out * (2.0 * err);
    let d_w_out_grad = &fwd.top_embed * (2.0 * err);
    let d_b_out_grad = 2.0 * err;

    // w_out 更新
    sw.m_w_out = &sw.m_w_out * sw.momentum + &d_w_out_grad * (1.0 - sw.momentum);
    sw.w_out = &sw.w_out - &sw.m_w_out * sw.lr;
    sw.m_b_out = sw.m_b_out * sw.momentum + d_b_out_grad * (1.0 - sw.momentum);
    sw.b_out -= sw.m_b_out * sw.lr;

    // ─── バックワード（ForwardCache を使用、再走査なし）──────────────────
    let mut dw1_acc: Array2<f64> = Array2::zeros(sw.w1.dim());
    let mut db1_acc: Array1<f64> = Array1::zeros(sw.b1.len());
    let mut dw2_acc: Array2<f64> = Array2::zeros(sw.w2.dim());
    let mut db2_acc: Array1<f64> = Array1::zeros(sw.b2.len());
    let mut d_leaf_acc: std::collections::HashMap<u64, Array1<f64>> = std::collections::HashMap::new();

    genome_backward_from_cache(
        genome, data, &fwd, sw,
        &d_h_final,
        &mut dw1_acc, &mut db1_acc, &mut dw2_acc, &mut db2_acc,
        &mut d_leaf_acc,
    );

    // ─── Muon 更新 ───────────────────────────────────────────────────────
    {
        let orth = newton_schulz_orthogonalize(&dw1_acc, 5);
        sw.m_w1 = &sw.m_w1 * sw.momentum + &orth * (1.0 - sw.momentum);
        sw.w1 = &sw.w1 - &sw.m_w1 * sw.lr;
    }
    {
        sw.m_b1 = &sw.m_b1 * sw.momentum + &db1_acc * (1.0 - sw.momentum);
        sw.b1 = &sw.b1 - &sw.m_b1 * sw.lr;
    }
    {
        let orth = newton_schulz_orthogonalize(&dw2_acc, 5);
        sw.m_w2 = &sw.m_w2 * sw.momentum + &orth * (1.0 - sw.momentum);
        sw.w2 = &sw.w2 - &sw.m_w2 * sw.lr;
    }
    {
        sw.m_b2 = &sw.m_b2 * sw.momentum + &db2_acc * (1.0 - sw.momentum);
        sw.b2 = &sw.b2 - &sw.m_b2 * sw.lr;
    }
    // leaf 埋め込み更新
    for (sig, d_emb) in d_leaf_acc {
        if let Some(emb) = sw.leaf_embeds.get_mut(&sig) {
            let mom = sw.m_leaf.entry(sig).or_insert_with(|| Array1::zeros(SURR_EMBED_DIM));
            *mom = &*mom * sw.momentum + &d_emb * (1.0 - sw.momentum);
            *emb = &*emb - &*mom * sw.lr;
        }
    }

    // embed_cache クリア（重みが変わったため）
    embed_cache.clear();

    mse
}

// ─── surrogate 予測（GenomeData を受け取るバージョン）────────────────────────
//
// 改善点:
//   - GenomeData を引数として受け取ることで、active_and_sig の再計算を排除。
//   - surrogate 評価フェーズでは呼び出し元が GenomeData を事前に計算して渡す。

fn surrogate_predict_with_data(
    genome: &Genome,
    data: &GenomeData,
    sw: &mut SurrogateWeights,
    embed_cache: &mut std::collections::HashMap<Sig, Array1<f64>>,
) -> f64 {
    // need_backward_cache=false: 推論のみなので NodeFwdEntry は作らない
    let fwd = genome_forward_with_cache(genome, data, sw, embed_cache, false);
    sw.predict_from_embed(&fwd.top_embed)
}

// ─── バリデーション相関（GenomeData を再利用）────────────────────────────────

fn update_val_correlation(
    sw: &mut SurrogateWeights,
    embed_cache: &mut std::collections::HashMap<Sig, Array1<f64>>,
) {
    if sw.held_out_buffer.len() < 8 { return; }
    let n_val = (sw.held_out_buffer.len() / 4).max(4).min(sw.held_out_buffer.len());
    let val_data: Vec<(u64, f64, Genome)> = sw.held_out_buffer[sw.held_out_buffer.len() - n_val..].to_vec();
    let mut preds: Vec<f64> = Vec::with_capacity(val_data.len());
    let mut trues: Vec<f64> = Vec::with_capacity(val_data.len());
    for (_, loss, g) in &val_data {
        // GenomeData を1回だけ計算して surrogate_predict_with_data に渡す
        let gd = GenomeData::new(g);
        preds.push(surrogate_predict_with_data(g, &gd, sw, embed_cache));
        trues.push(*loss);
    }
    let corr = pearson_1d(&preds, &trues).abs();
    sw.val_correlation = sw.val_correlation * 0.7 + corr * 0.3;
}

fn update_surrogate_multiplier(sw: &mut SurrogateWeights) {
    if sw.val_correlation > SURR_PROMOTE_THRESH {
        sw.surrogate_multiplier = (sw.surrogate_multiplier * 1.2).min(SURR_MAX_MULTIPLIER);
        eprintln!("  [surrogate] promoted: multiplier → {:.2}", sw.surrogate_multiplier);
    } else if sw.val_correlation < SURR_DEMOTE_THRESH {
        sw.surrogate_multiplier = (sw.surrogate_multiplier * 0.8).max(0.1);
        eprintln!("  [surrogate] demoted:  multiplier → {:.2}", sw.surrogate_multiplier);
    }
}

// ─── Evaluator ────────────────────────────────────────────────────────────────

struct Evaluator {
    node_cache: DashMap<Sig, ArcVec>,
    adf_cache: DashMap<AdfKey, (Sig, ArcVec)>,
    fitness_cache: DashMap<u64, Score>,
    score_cache: DashMap<(Sig, Sig), Score>,
}

impl Evaluator {
    fn new() -> Self {
        Self {
            node_cache: DashMap::with_capacity(1 << 17),
            adf_cache: DashMap::with_capacity(1 << 16),
            fitness_cache: DashMap::with_capacity(POP_SIZE * 8),
            score_cache: DashMap::with_capacity(1 << 17),
        }
    }
    fn reset_generation(&self) {
        self.node_cache.clear();
        if self.adf_cache.len() > ADF_CACHE_MAX {
            self.adf_cache.clear();
            self.score_cache.clear();
        }
    }
    fn get_node_score(&self, batch_sig: Sig, node_sig: Sig, val: &ArcVec, target: &[Complex<f64>],
        p_buf: &mut [f64], t_buf: &mut [f64], order_buf: &mut [usize], rank_buf: &mut [i64]) -> Score
    {
        let key = (batch_sig, node_sig);
        if let Some(s) = self.score_cache.get(&key) { return *s; }
        let s = score_and_acc_into(val, target, p_buf, t_buf, order_buf, rank_buf);
        self.score_cache.insert(key, s); s
    }
}

// ─── 評価指標 ─────────────────────────────────────────────────────────────────

fn pearson_raw(x: &[f64], y: &[f64]) -> f64 {
    let n = x.len() as f64;
    let mx = x.iter().sum::<f64>() / n;
    let my = y.iter().sum::<f64>() / n;
    let (mut num, mut dx, mut dy) = (0.0, 0.0, 0.0f64);
    for (&xi, &yi) in x.iter().zip(y) {
        let a = xi - mx; let b = yi - my;
        num += a * b; dx += a * a; dy += b * b;
    }
    if dx < 1e-12 || dy < 1e-12 { 0.0 } else { num / (dx.sqrt() * dy.sqrt()) }
}

#[inline]
fn chatterjee_from_ranks(sorted_idx: &[usize], ranks: &[i64]) -> f64 {
    let s: i64 = sorted_idx.windows(2).map(|w| (ranks[w[0]] - ranks[w[1]]).abs()).sum();
    let n = sorted_idx.len() as f64;
    1.0 - 3.0 * s as f64 / (n * n - 1.0)
}

fn score_and_acc_into(pred: &[Complex<f64>], target: &[Complex<f64>],
    p_buf: &mut [f64], t_buf: &mut [f64], order_buf: &mut [usize], rank_buf: &mut [i64]) -> (f64, f64)
{
    let n = pred.len();
    let extractors: [fn(Complex<f64>) -> f64; 4] = [|z| z.re, |z| z.im, |z| z.norm(), |z| z.arg()];
    let mut total_score = 0.0f64;
    let mut max_pearson = 0.0f64;
    let mut p_rank_buf = vec![0i64; n];
    let mut t_order_buf = vec![0usize; n];
    for ext in extractors {
        for k in 0..n { p_buf[k] = ext(pred[k]); t_buf[k] = ext(target[k]); }
        for k in 0..n { order_buf[k] = k; }
        order_buf[..n].sort_unstable_by(|&a, &b| p_buf[a].partial_cmp(&p_buf[b]).unwrap_or(std::cmp::Ordering::Equal));
        for (r, &i) in order_buf[..n].iter().enumerate() { p_rank_buf[i] = r as i64; }
        for k in 0..n { t_order_buf[k] = k; }
        t_order_buf[..n].sort_unstable_by(|&a, &b| t_buf[a].partial_cmp(&t_buf[b]).unwrap_or(std::cmp::Ordering::Equal));
        for (r, &i) in t_order_buf[..n].iter().enumerate() { rank_buf[i] = r as i64; }
        let c_fwd = chatterjee_from_ranks(&order_buf[..n], rank_buf);
        let c_bwd = chatterjee_from_ranks(&t_order_buf[..n], &p_rank_buf);
        let pe = pearson_raw(&p_buf[..n], &t_buf[..n]).abs();
        total_score += (1.0 - ((((c_fwd.max(0.0).powf(C) + c_bwd.max(0.0).powf(C)) / 2.0) * (1.0 - D) + pe.powf(C) * D)).powf(1.0 / C)).powf(E);
        if pe > max_pearson { max_pearson = pe; }
    }
    (total_score / 4.0, max_pearson)
}

// ─── 汎用 ADF 実行 ────────────────────────────────────────────────────────────

fn exec_adf(
    layer_idx: usize, c: &Chromosome, c_sig: Sig, active: &[usize],
    in0_sig: Sig, in0: &ArcVec, in1_sig: Sig, in1: &ArcVec, one: &ArcVec,
    x_sig: Sig, x_arc: &ArcVec,
    genome: &Genome, all_sigs: &[Vec<Sig>], all_acts: &[Vec<Vec<usize>>],
    batch_sig: Sig, ev: &Evaluator,
) -> (Sig, ArcVec) {
    let key: AdfKey = (batch_sig, c_sig, in0_sig, in1_sig, x_sig);
    if let Some(v) = ev.adf_cache.get(&key) { return (v.0, Arc::clone(&v.1)); }
    let n_ext = N_INPUTS_ADF;
    let total = n_ext + layer_len(layer_idx);
    let mut buf = NodeBuf::new(total);
    buf.set(0, in0_sig, Arc::clone(in0));
    buf.set(1, in1_sig, Arc::clone(in1));
    buf.set(2, ONE_SIG, Arc::clone(one));
    buf.set(3, x_sig,   Arc::clone(x_arc));
    for &abs in active {
        if abs < n_ext { continue; }
        let i = abs - n_ext;
        let c0 = c.conn[i][0] as usize;
        let c1 = c.conn[i][1] as usize;
        let s0 = buf.sig(c0); let s1 = buf.sig(c1);
        let f = c.func[i] as usize;
        let (sig, val) = if f == 0 || layer_idx == 0 {
            let sig = make_sig(s0, s1, 0);
            let val = node_get_or_compute(sig, buf.val(c0), buf.val(c1), ev);
            (sig, val)
        } else {
            let sub_li = layer_idx - 1;
            let sub_idx = (f - 1).min(layer_n_adf(sub_li) - 1);
            exec_adf(
                sub_li, &genome.layers[sub_li][sub_idx], all_sigs[sub_li][sub_idx],
                &all_acts[sub_li][sub_idx], s0, buf.val(c0), s1, buf.val(c1), one,
                x_sig, x_arc, genome, all_sigs, all_acts, batch_sig, ev,
            )
        };
        buf.set(abs, sig, val);
    }
    let result = (buf.sig(total - 1), Arc::clone(buf.val(total - 1)));
    ev.adf_cache.entry(key).or_insert_with(|| result.clone());
    result
}

// ─── 最終出力層 実行 ──────────────────────────────────────────────────────────

fn exec_top(
    genome: &Genome, top_active: &[usize], all_sigs: &[Vec<Sig>], all_acts: &[Vec<Vec<usize>>],
    ext: &[Vec<Complex<f64>>; N_INPUTS_MAIN], target: &[Complex<f64>],
    batch_sig: Sig, ev: &Evaluator,
    p_buf: &mut [f64], t_buf: &mut [f64], order_buf: &mut [usize], rank_buf: &mut [i64],
) -> (ArcVec, Sig, f64, usize) {
    let top_li = N_LAYERS - 1;
    let c = &genome.layers[top_li][0];
    let n_ext = N_INPUTS_MAIN;
    let total = n_ext + layer_len(top_li);
    let mut buf = NodeBuf::new(total);
    for i in 0..n_ext { buf.set(i, i as Sig + 1, Arc::from(ext[i].as_slice())); }
    let one_arc: ArcVec = Arc::from(ext[1].as_slice());
    let x_arc: ArcVec = Arc::from(ext[0].as_slice());
    let x_sig: Sig = 1;
    let mut sum_score = 0.0; let mut count = 0;
    for &abs in top_active {
        if abs < n_ext { continue; }
        let i = abs - n_ext;
        let c0 = c.conn[i][0] as usize; let c1 = c.conn[i][1] as usize;
        let s0 = buf.sig(c0); let s1 = buf.sig(c1);
        let f = c.func[i] as usize;
        let (sig, val) = if f == 0 || top_li == 0 {
            let sig = make_sig(s0, s1, 0);
            let val = node_get_or_compute(sig, buf.val(c0), buf.val(c1), ev);
            (sig, val)
        } else {
            let sub_li = top_li - 1;
            let sub_idx = (f - 1).min(layer_n_adf(sub_li) - 1);
            exec_adf(
                sub_li, &genome.layers[sub_li][sub_idx], all_sigs[sub_li][sub_idx],
                &all_acts[sub_li][sub_idx], s0, buf.val(c0), s1, buf.val(c1), &one_arc,
                x_sig, &x_arc, genome, all_sigs, all_acts, batch_sig, ev,
            )
        };
        let (s, _) = ev.get_node_score(batch_sig, sig, &val, target, p_buf, t_buf, order_buf, rank_buf);
        sum_score += s; count += 1;
        buf.set(abs, sig, val);
    }
    let out_sig = buf.sig(total - 1);
    (Arc::clone(buf.val(total - 1)), out_sig, sum_score, count)
}

// ─── Fitness 評価 ─────────────────────────────────────────────────────────────

fn eval(g: &Genome, ds: &Dataset, ev: &Evaluator, inter_weight: f64) -> (f64, f64) {
    let top_li = N_LAYERS - 1;
    let all_data: Vec<Vec<(Vec<usize>, Sig)>> = (0..N_LAYERS)
        .map(|li| g.layers[li].iter().map(|c| c.active_and_sig()).collect()).collect();
    let all_sigs: Vec<Vec<Sig>> = all_data.iter()
        .map(|layer| layer.iter().map(|d| d.1).collect()).collect();
    let all_acts: Vec<Vec<Vec<usize>>> = all_data.into_iter()
        .map(|layer| layer.into_iter().map(|d| d.0).collect()).collect();
    let top_active = &all_acts[top_li][0];
    let genome_base = genome_key(&all_sigs);
    let top_sig = all_sigs[top_li][0];
    let gkey = make_sig(make_sig(genome_base, ds.batch_sig, 0), inter_weight.to_bits(), 1);
    if let Some(v) = ev.fitness_cache.get(&gkey) { return *v; }
    let mut p_buf = vec![0.0f64; VEC_LEN];
    let mut t_buf = vec![0.0f64; VEC_LEN];
    let mut order_buf = vec![0usize; VEC_LEN];
    let mut rank_buf = vec![0i64; VEC_LEN];
    let mut total_loss = 0.0; let mut total_acc = 0.0;
    for (inputs, target) in &ds.batches {
        let (pred, out_sig, sum_score, count) = exec_top(
            g, top_active, &all_sigs, &all_acts, inputs, target, ds.batch_sig, ev,
            &mut p_buf, &mut t_buf, &mut order_buf, &mut rank_buf);
        let (_final_s, final_a) = ev.get_node_score(ds.batch_sig, out_sig, &pred, target,
            &mut p_buf, &mut t_buf, &mut order_buf, &mut rank_buf);
        let avg_inter = if count > 0 { (sum_score / count as f64).powf(1.0 / E) } else { 0.0 };
        let combined = avg_inter;
        total_loss += ((combined).powf(A) * B + (1.0 - final_a).powf(A) * (1.0 - B)).powf(1.0 / A);
        total_acc += final_a;
    }
    let _ = top_sig;
    let n = ds.batches.len() as f64;
    let res = (total_loss / n, total_acc / n);
    ev.fitness_cache.insert(gkey, res); res
}

// ─── Main ─────────────────────────────────────────────────────────────────────

fn main() {
    assert_eq!(LAYER_LEN.len(), N_LAYERS);
    assert_eq!(N_ADF_PER_LAYER.len(), N_LAYERS - 1);
    assert!(N_LAYERS >= 1);

    eprintln!(
        "ADF-CGP+Surrogate  N_LAYERS={N_LAYERS}  LAYER_LEN={:?}  POP={POP_SIZE}  SURR_EMBED={SURR_EMBED_DIM}  SURR_HIDDEN={SURR_HIDDEN_DIM}  SURR_LR={SURR_LR}  SURR_RATIO={SURR_RATIO_INIT}",
        LAYER_LEN,
    );

    let mut rng = SmallRng::seed_from_u64(42);
    let ds = Dataset::new_fixed(&mut rng);
    let mut pop: Vec<Genome> = (0..POP_SIZE).map(|_| Genome::random(&mut rng)).collect();
    let evaluator = Evaluator::new();

    let mut sw = SurrogateWeights::new(SURR_LR);
    let mut embed_cache: std::collections::HashMap<Sig, ndarray::Array1<f64>> =
        std::collections::HashMap::new();
    let mut surr_step_accumulator: f64 = 0.0;
    let mut n_real_evals: usize = 0;

    for gen in 0..N_GEN {
        evaluator.reset_generation();
        let inter_weight = INTER_WEIGHT_MAX * (gen as f64 / CURRICULUM_RAMP_GENS as f64).min(1.0);

        // ─── 実評価フェーズ ────────────────────────────────────────────────────
        let mut scored: Vec<(f64, f64, Genome)> = pop
            .par_iter()
            .map(|g| { let (l, a) = eval(g, &ds, &evaluator, inter_weight); (l, a, g.clone()) })
            .collect();
        scored.sort_unstable_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal));

        println!(
            "CMAES_ACC gen={} loss={:.10} acc={:.10} surr_mult={:.3} surr_corr={:.3}",
            gen, scored[0].0, scored[0].1, sw.surrogate_multiplier, sw.val_correlation,
        );

        // ─── Surrogate 訓練フェーズ ────────────────────────────────────────────
        // elite を 訓練用 / held-out 用に 3:1 で分割
        let n_train_elites = (ELITE * 3 / 4).max(1);
        let _n_held_out    = ELITE - n_train_elites;
        let mut surr_mse_sum = 0.0f64;

        // 訓練用 elites: GenomeData を1回計算してフォワード+バックワードに渡す
        for k in 0..n_train_elites.min(scored.len()) {
            let actual_loss = scored[k].0;
            let gd = GenomeData::new(&scored[k].2);
            let mse = surrogate_train_step(&mut sw, &scored[k].2, &gd, actual_loss, &mut embed_cache);
            surr_mse_sum += mse;
        }
        n_real_evals += n_train_elites;

        // held-out バッファに追加
        for k in n_train_elites..ELITE.min(scored.len()) {
            let gk = GenomeData::new(&scored[k].2).genome_key;
            sw.held_out_buffer.push((gk, scored[k].0, scored[k].2.clone()));
            if sw.held_out_buffer.len() > 500 {
                sw.held_out_buffer.drain(..50);
            }
        }

        // held-out セットでバリデーション相関を更新
        update_val_correlation(&mut sw, &mut embed_cache);
        update_surrogate_multiplier(&mut sw);

        eprintln!(
            "  [surrogate] gen={} train_mse_avg={:.6} val_corr={:.4} n_real={} mult={:.2}",
            gen,
            surr_mse_sum / n_train_elites as f64,
            sw.val_correlation,
            n_real_evals,
            sw.surrogate_multiplier,
        );

        // ─── 次世代生成 ───────────────────────────────────────────────────────
        let elites: Vec<Genome> = scored[..ELITE].iter().map(|x| x.2.clone()).collect();
        let mut next = elites.clone();

        surr_step_accumulator += SURR_RATIO_INIT * sw.surrogate_multiplier;
        let actual_surr_steps = surr_step_accumulator as usize;
        surr_step_accumulator -= actual_surr_steps as f64;

        if sw.val_correlation > 0.3 && actual_surr_steps > 0 {
            for _surr_gen in 0..actual_surr_steps {
                // surrogate 評価フェーズ: embed_cache を世代内で共有する
                // (重みは変わっていないため、サブツリーの共有が有効)
                // embed_cache は前の学習ステップで clear 済み
                let mut surr_candidates: Vec<Genome> = Vec::with_capacity(POP_SIZE);
                for _ in 0..(POP_SIZE - ELITE) {
                    let p1 = &scored[rng.gen_range(0..ELITE)].2;
                    let p2 = &scored[rng.gen_range(0..ELITE)].2;
                    let child = match rng.gen_range(0..3u8) {
                        0 => p1.mix(&mut rng, p2),
                        1 => p1.mutate(&mut rng),
                        _ => p1.mix(&mut rng, p2).mutate(&mut rng),
                    };
                    surr_candidates.push(child);
                }

                // GenomeData を各候補について1回だけ計算し surrogate_predict_with_data に渡す
                // embed_cache はこのフェーズ全体で共有される（重みは変化しない）
                let mut surr_all: Vec<(f64, Genome)> = surr_candidates
                    .into_iter()
                    .map(|g| {
                        let gd = GenomeData::new(&g);
                        let s = surrogate_predict_with_data(&g, &gd, &mut sw, &mut embed_cache);
                        (s, g)
                    })
                    .collect();
                let mut elite_scored: Vec<(f64, Genome)> = next.iter()
                    .map(|g| {
                        let gd = GenomeData::new(g);
                        let s = surrogate_predict_with_data(g, &gd, &mut sw, &mut embed_cache);
                        (s, g.clone())
                    })
                    .collect();
                surr_all.append(&mut elite_scored);
                surr_all.sort_unstable_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal));
                next = surr_all.into_iter().take(POP_SIZE).map(|x| x.1).collect();

                // surr_gen をまたぐ場合は embed_cache をクリア（重みは変化していないが
                // 次の surr_gen では異なる候補群なのでキャッシュの意義は薄い）
                // 注: 重みは変化しないため実はクリア不要だが、メモリ節約のため行う
                // embed_cache.clear();  // コメントアウト: 重みが変わらないなら保持した方が速い
            }
            pop = next;
        } else {
            while next.len() < POP_SIZE {
                let p1 = &scored[rng.gen_range(0..ELITE)].2;
                let p2 = &scored[rng.gen_range(0..ELITE)].2;
                let child = match rng.gen_range(0..3u8) {
                    0 => p1.mix(&mut rng, p2),
                    1 => p1.mutate(&mut rng),
                    _ => p1.mix(&mut rng, p2).mutate(&mut rng),
                };
                next.push(child);
            }
            pop = next;
        }
    }
}

/// 1D ピアソン相関
fn pearson_1d(x: &[f64], y: &[f64]) -> f64 {
    let n = x.len() as f64;
    if n < 2.0 { return 0.0; }
    let mx = x.iter().sum::<f64>() / n;
    let my = y.iter().sum::<f64>() / n;
    let (mut num, mut dx, mut dy) = (0.0f64, 0.0f64, 0.0f64);
    for (&xi, &yi) in x.iter().zip(y) {
        let a = xi - mx; let b = yi - my;
        num += a * b; dx += a * a; dy += b * b;
    }
    if dx < 1e-14 || dy < 1e-14 { 0.0 } else { num / (dx.sqrt() * dy.sqrt()) }
}
"""


def generate_rust_source(params: dict) -> str:
    n = params["N_LAYERS"]
    llen = params["LAYER_LEN"]
    llen2 = params["LAYER_LEN_LAST"]
    nadf = params["N_ADF_PER_LAYER"]

    layer_len_arr = ", ".join([str(llen)] * (n - 1) + [str(llen2)])
    n_adf_arr = "" if n == 1 else ", ".join([str(nadf)] * (n - 1))

    elite = params["ELITE"]
    pop_size = params["POP_SIZE"]
    elite = min(elite, pop_size // 2)
    elite = max(elite, 2)

    src = RUST_TEMPLATE.format(
        N_LAYERS=n,
        LAYER_LEN_ARR=layer_len_arr,
        N_ADF_ARR=n_adf_arr,
        VEC_LEN=params["VEC_LEN"],
        POP_SIZE=pop_size,
        ELITE=elite,
        PROB_EML=f"{params['PROB_EML']:.8f}",
        A=f"{params['A']:.8f}",
        B=f"{params['B']:.8f}",
        C=f"{params['C']:.8f}",
        D=f"{params['D']:.8f}",
        E=f"{params['E']:.8f}",
        HILO=f"{params['HILO']:.8f}",
        P=f"{params['P']:.8f}",
        MUT_STOP_PROB=f"{params['MUT_STOP_PROB']:.8f}",
        MUT_MAX_TARGETS=params["MUT_MAX_TARGETS"],
        SURR_EMBED_DIM=params["SURR_EMBED_DIM"],
        SURR_HIDDEN_DIM=params["SURR_HIDDEN_DIM"],
        SURR_LR=f"{params['SURR_LR']:.8f}",
        SURR_RATIO=f"{params['SURR_RATIO']:.8f}",
        SURR_PROMOTE_THRESH=f"{params['SURR_PROMOTE_THRESH']:.8f}",
        SURR_DEMOTE_THRESH=f"{params['SURR_DEMOTE_RATIO'] * params['SURR_PROMOTE_THRESH']:.8f}",
        SURR_MAX_MULTIPLIER=f"{params['SURR_MAX_MULTIPLIER']:.8f}",
        BODY=RUST_BODY,
    )
    return src


# ─── ビルド & 実行 ────────────────────────────────────────────────────────────

def build_and_run(params: dict, project_dir: str, eval_time: int, trial_idx: int, out_dir: str) -> float:
    src = generate_rust_source(params)
    src_path = os.path.join(project_dir, "src", "main.rs")
    with open(src_path, "w", encoding="utf-8") as f:
        f.write(src)

    log_dir = os.path.join(out_dir, f"trial_{trial_idx:04d}")
    os.makedirs(log_dir, exist_ok=True)
    with open(os.path.join(log_dir, "params.json"), "w") as f:
        json.dump(params, f, indent=2)

    print(f"  [trial {trial_idx}] Building ...", flush=True)
    build_start = time.time()
    build_result = subprocess.run(
        ["cargo", "build", "--release"],
        cwd=project_dir, capture_output=True, text=True, timeout=300,
    )
    build_elapsed = time.time() - build_start

    if build_result.returncode != 0:
        print(f"  [trial {trial_idx}] BUILD FAILED ({build_elapsed:.1f}s)")
        print(build_result.stderr[-2000:])
        with open(os.path.join(log_dir, "build_stderr.txt"), "w") as f:
            f.write(build_result.stderr)
        return 0.0

    print(f"  [trial {trial_idx}] Build OK ({build_elapsed:.1f}s). Running {eval_time}s ...", flush=True)

    bin_name = None
    cargo_toml = os.path.join(project_dir, "Cargo.toml")
    try:
        import tomllib
        with open(cargo_toml, "rb") as f:
            toml_data = tomllib.load(f)
        bin_name = toml_data.get("package", {}).get("name", None)
    except Exception:
        pass
    if bin_name is None:
        for line in open(cargo_toml):
            m = re.match(r'\s*name\s*=\s*"([^"]+)"', line)
            if m:
                bin_name = m.group(1)
                break
    if bin_name is None:
        bin_name = os.path.basename(project_dir)

    binary = os.path.join(project_dir, "target", "release", bin_name)
    run_proc = subprocess.Popen(
        [binary], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True, cwd=project_dir,
    )

    import select as _select
    lines = []
    deadline = time.time() + eval_time
    last_output_time = time.time()
    SILENCE_TIMEOUT = 20.0
    timed_out_by_silence = False

    try:
        while True:
            now = time.time()
            if now >= deadline:
                break
            if now - last_output_time >= SILENCE_TIMEOUT:
                timed_out_by_silence = True
                break

            time_to_deadline = deadline - now
            time_to_silence   = SILENCE_TIMEOUT - (now - last_output_time)
            wait = min(time_to_deadline, time_to_silence, 1.0)

            ready, _, _ = _select.select([run_proc.stdout], [], [], wait)
            if not ready:
                continue
            line = run_proc.stdout.readline()
            if not line:
                break
            last_output_time = time.time()
            lines.append(line.rstrip())
            if "CMAES_ACC" in line:
                print(f"    {line.rstrip()}", flush=True)
    finally:
        run_proc.terminate()
        try:
            run_proc.wait(timeout=20)
        except subprocess.TimeoutExpired:
            run_proc.kill()

    with open(os.path.join(log_dir, "stdout.txt"), "w") as f:
        f.write("\n".join(lines))

    if timed_out_by_silence:
        print(f"  [trial {trial_idx}] INVALID: no output for {SILENCE_TIMEOUT:.0f}s → acc = None")
        with open(os.path.join(log_dir, "result.json"), "w") as f:
            json.dump({"acc": None, "invalid": "silence_timeout", **params}, f, indent=2)
        return None

    i = 0.0
    best_acc = 0.0
    for line in lines:
        m = re.search(r"CMAES_ACC.*acc=([0-9.]+)", line)
        if m:
            try:
                best_acc += math.log(max(1 - float(m.group(1)), 1e-24))
                i += 1
            except ValueError:
                pass
    best_acc = 1.0 - math.exp(best_acc / i) if i > 0 else 0.0

    print(f"  [trial {trial_idx}] acc = {best_acc:.6f}")
    with open(os.path.join(log_dir, "result.json"), "w") as f:
        json.dump({"acc": best_acc, **params}, f, indent=2)
    return best_acc


# ─── CMA-ES ループ ────────────────────────────────────────────────────────────

class CMAESSearcher:
    def __init__(self, project_dir: str, eval_time: int, budget: int, out_dir: str):
        self.project_dir = project_dir
        self.eval_time = eval_time
        self.budget = budget
        self.out_dir = out_dir
        self.history = []
        self.trial_idx = 0

        os.makedirs(out_dir, exist_ok=True)

        x0 = initial_x()
        sigma0 = initial_sigma()

        bounds_lo, bounds_hi = [], []
        for name, lo, hi, init, is_int, log_scale in PARAM_DEFS:
            if log_scale:
                bounds_lo.append(math.log(max(lo, 1e-9)))
                bounds_hi.append(math.log(hi))
            else:
                bounds_lo.append(float(lo))
                bounds_hi.append(float(hi))

        opts = cma.CMAOptions()
        opts["bounds"] = [bounds_lo, bounds_hi]
        opts["maxfevals"] = budget
        opts["verbose"] = -9
        opts["tolx"] = 1e-4
        opts["popsize"] = 32
        opts["tolfun"] = 1e-4

        self.es = cma.CMAEvolutionStrategy(x0, sigma0, opts)
        print(f"CMA-ES initialized: dim={len(x0)}, sigma0={sigma0:.3f}, budget={budget}")
        print(f"Params: {[p[0] for p in PARAM_DEFS]}")

    def objective(self, x: list) -> float:
        params = decode(x)
        print(f"\n{'='*60}")
        print(f"Trial {self.trial_idx}: {params}")
        acc = build_and_run(params, self.project_dir, self.eval_time, self.trial_idx, self.out_dir)
        self.trial_idx += 1

        if acc is None:
            self.history.append({"trial": self.trial_idx - 1, "acc": None, "invalid": True, **params})
            self._save_history()
            return 0.0

        EPS = 1e-24
        fitness = math.log(max(1.0 - acc, EPS))
        self.history.append({"trial": self.trial_idx - 1, "acc": acc, **params})
        self._save_history()
        return fitness

    def run(self):
        print("\n" + "="*60)
        print("Starting CMA-ES hyperparameter search (with Surrogate Model)")
        print("="*60)

        global_best_fitness = float("inf")
        global_best_params = None

        while not self.es.stop() and self.trial_idx < self.budget:
            solutions = self.es.ask()
            fitnesses = [self.objective(x) for x in solutions]
            self.es.tell(solutions, fitnesses)

            iter_best_idx = int(min(range(len(fitnesses)), key=lambda i: fitnesses[i]))
            iter_best_fitness = fitnesses[iter_best_idx]
            iter_best_params = decode(solutions[iter_best_idx])

            if iter_best_fitness < global_best_fitness:
                global_best_fitness = iter_best_fitness
                global_best_params = iter_best_params

            global_best_acc = 1.0 - math.exp(min(global_best_fitness, 0.0))
            iter_best_acc = 1.0 - math.exp(min(iter_best_fitness, 0.0))
            print(
                f"\n>>> iter best: acc≈{iter_best_acc:.6f} | "
                f"global best: acc≈{global_best_acc:.6f} params={global_best_params}"
            )

        print("\n" + "="*60)
        print("CMA-ES search finished.")
        if self.history:
            valid = [d for d in self.history if d.get("acc") is not None]
            if valid:
                best = max(valid, key=lambda d: d["acc"])
                print(f"Best trial #{best['trial']}: acc={best['acc']:.6f}")
                print(f"Best params: { {k: v for k, v in best.items() if k not in ('trial','acc')} }")
                with open(os.path.join(self.out_dir, "best_params.json"), "w") as f:
                    json.dump(best, f, indent=2)
                print(f"Saved to {self.out_dir}/best_params.json")
        return self.history

    def _save_history(self):
        with open(os.path.join(self.out_dir, "history.json"), "w") as f:
            json.dump(self.history, f, indent=2)


# ─── Cargo.toml テンプレート ─────────────────────────────────────────────────

CARGO_TOML_TEMPLATE = """\
[package]
name = "adf_cgp"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
dashmap = "5"
ndarray = { version = "0.15", features = ["rayon"] }
num-complex = "0.4"
rand = { version = "0.8", features = ["small_rng"] }
rayon = "1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
"""


def setup_project(project_dir: str, src_rs_path: Optional[str] = None):
    src_dir = os.path.join(project_dir, "src")
    os.makedirs(src_dir, exist_ok=True)

    cargo_toml = os.path.join(project_dir, "Cargo.toml")
    if not os.path.exists(cargo_toml):
        print(f"Creating new Cargo project at {project_dir}")
        with open(cargo_toml, "w") as f:
            f.write(CARGO_TOML_TEMPLATE)
    else:
        content = open(cargo_toml).read()
        if "ndarray" not in content:
            print("Adding ndarray to Cargo.toml ...")
            content = content.replace(
                '[dependencies]',
                '[dependencies]\nndarray = { version = "0.15", features = ["rayon"] }'
            )
            with open(cargo_toml, "w") as f:
                f.write(content)

    src_dest = os.path.join(src_dir, "main.rs")
    if src_rs_path and os.path.exists(src_rs_path):
        shutil.copy2(src_rs_path, src_dest)
        print(f"Copied {src_rs_path} → {src_dest}")
    elif not os.path.exists(src_dest):
        params = {name: init for name, lo, hi, init, is_int, log_scale in PARAM_DEFS}
        with open(src_dest, "w") as f:
            f.write(generate_rust_source(params))
        print(f"Generated initial main.rs at {src_dest}")


# ─── エントリポイント ─────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="CMA-ES hyperparameter search for ADF-CGP (with Surrogate Model)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
        例:
          python3 cmaes_search.py --project . --budget 30 --time 30
          python3 cmaes_search.py --project ./adf_cgp_proj --src main.rs --budget 30 --time 30
        """),
    )
    parser.add_argument("--project", default=".", help="Cargo プロジェクトのルートディレクトリ")
    parser.add_argument("--src", default=None, help="元の main.rs パス")
    parser.add_argument("--out", default=DEFAULT_OUT, help="結果出力ディレクトリ")
    parser.add_argument("--budget", type=int, default=DEFAULT_BUDGET)
    parser.add_argument("--time", type=int, default=DEFAULT_TIME)
    args = parser.parse_args()

    project_dir = os.path.abspath(args.project)
    out_dir = os.path.abspath(args.out)

    print(f"Project dir : {project_dir}")
    print(f"Output dir  : {out_dir}")
    print(f"Budget      : {args.budget} evaluations")
    print(f"Eval time   : {args.time} seconds each")

    setup_project(project_dir, args.src)

    searcher = CMAESSearcher(
        project_dir=project_dir,
        eval_time=args.time,
        budget=args.budget,
        out_dir=out_dir,
    )
    searcher.run()


if __name__ == "__main__":
    main()